### ISSUE TITLE
[BUG] Intellisense fails when you open a project without internet access

### ISSUE THREAD

**Issue by macromaniac** [microsoft/vscode-dotnettools#1028]
### Describe the Issue

After disconnecting from internet and opening a project it seems like C# dev kit (or something) hangs and I get no intellisense. Typically I do development without internet access so it's a bit annoying.

### Steps To Reproduce

1. Run "ipconfig /release" (after you are done ipconfig /renew restores internet, can also unplug I assume)
2. Open the vscode dev kit project
3. Observe intellisense not working, here are some logs:

> Starting Spawn .NET server...
> Starting Open a solution...
> Starting Open a solution with environment service...
> Starting Clear environment...

### Expected Behavior

With internet:

> Starting Spawn .NET server...
> Starting Open a solution...
> Starting Open a solution with environment service...
> Starting Clear environment...
> Using local .NET runtime at "c:\Users\joeyc\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\8.0.3~x64\dotnet.exe"
> .NET server started and IPC established in 1028m

### Environment Information

C# dev kit info: 
2024-03-17, 12:59:53

Edition	Windows 10 Home
Version	22H2
Installed on	‎2/‎13/‎2021
OS build	19045.4170
Experience	Windows Feature Experience Pack 1000.19054.1000.0

Device name	gme
Processor	AMD Ryzen 9 3950X 16-Core Processor               3.49 GHz
Installed RAM	32.0 GB
Device ID	458A4073-198F-412D-9B2D-CB35512EAABA
Product ID	00326-11250-10002-AA650
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by dibarbet** [comment]
This appears to be an issue launching the devkit server.  Moving over to the extension management area path.

**Comment by AArnott** [comment]
I can repro this today, only if there is no .NET 8 runtime globally installed. From this I surmise that the hang comes from the .NET runtime acquisition extension. I _did_ already load C# Dev Kit on a prior session with the Internet and the .NET acquisition extension downloaded a VS Code extension local copy of the .NET 8 runtime. So it _should_ have everything it needs to work offline.

My guess is the acquisition extension is trying to see if the 8.0.6 runtime that it downloaded on my last session is still recent enough to return as the path for C# Dev Kit to use, and doesn't have a timeout or any other way to realize the Internet is down and it'll be waiting indefinitely.

**Comment by reimakesgames** [comment]
Any estimate when this issue will be fixed? it will be of great help for people who want to develop offline. Thanks!

**Comment by nagilson** [comment]
The .NET Install Tool has a timeout for all web requests, but the default is relatively long at 10 minutes. You can change this in the extension settings and see if that is indeed the problem @AArnott ?

The tool does have logic in place which checks if you already have an install, but it only considers an exact version to be a match for the install. C# DevKit passes the version as '8.0' which needs to be resolved to a specific version such as '8.0.6', but you can also pass the fully specified version. However, the version resolution logic needs the internet to see what's the newest version available, so it will fail eventually, it's just going to take some time.

The acquire status command works similarly.

One solution is for us to add some logic to check the status if a specific version is given without checking the internet.
But to do so, I think vs-green would need to preserve/cache the version it had installed previously and then if its offline or fails try to acquire with that and check the status. (Or save the path, but this is not recommended.)

From the perspective of making whats happening more clear, the .NET Install Tool does make itself show up in the console during install and show an installation in progress. Shortening the timeout value by default will not go well so I'm not sure what else we'd do there.

**Comment by AArnott** [comment]
@nagilson in my testing, the ".NET Install Tool" output window didn't log anything during this hang. I set the timeout in settings to just 10 seconds, but long after 10 seconds expired, I'm still looking at a blank output window pane both for the ".NET Install Tool" extension and C# Dev Kit still hangs as described in the OP.

Incidentally, the first time I launched VS Code to give the acquisition extension a chance to download the runtime, the output window pane was empty then too, even though it had obviously succeeded since C# Dev Kit was running.

**Comment by AArnott** [comment]
Also IMO if C# Dev Kit asks for `8.0` and `8.0.6` is already installed, that should be plenty good enough to immediately return without a web call to make sure that's the latest. A web call could still be made, concurrently, and if there's something later by all means download it for the next session. But holding up the current session when you already have a qualifying runtime seems bad in any case -- especially if your extension can't tell the difference between a slow response and no Internet connection.
On that note by the way, I'm pretty certain there's a way to tell the difference. But I'm surprised it isn't expressed as an immediately failed javascript promise, since the OS shouldn't leave an HTTP request dangling with no transport to use.

**Comment by nagilson** [comment]
>  long after 10 seconds expired, I'm still looking at a blank output window pane

Thanks for taking the time to try it out.
I experienced the same result. I understand why this is happening. If youre not curious, skip to the other parts. 
I can release a fix for this but I am a bit hesitant because removing this increased install success rates by quite a bit, but it's hard to tease apart because the comparison is between version 1.8.1 and 2.0.0 which have significantly different code.

We will probably try it out in the next release because I think the risk is lower, will just need to QA it a lot.

1. C# code calls acquireStatus before acquire. AcquireStatus does not have any output to the console.
2. Axios (web request library we use) has a bug with no connection timeouts. Its timeout handler only works with request timeouts, not no connection timeouts. More at https://stackoverflow.com/questions/36690451/timeout-feature-in-the-axios-library-is-not-working. So yeah, it's going to be stuck forever waiting for a connection.

I fixed #2 in the past by adding a custom timeout with a cancellation token. https://github.com/dotnet/vscode-dotnet-runtime/commit/ced82f31501c63202344ba3dff74885480b6ff1d#diff-ad11027eb5a8406f68425da0e49b1c8a4aa83394444043e247c10e7bb1976999

It looks like I got rid of that because I forgot about the axios timeout issue. https://github.com/dotnet/vscode-dotnet-runtime/commit/3b1c2512c57266ec7ed9e1fb041d3754f1d6e45f

> Incidentally, the first time I launched VS Code to give the acquisition extension a chance to download the runtime, the output window pane was empty then too, even though it had obviously succeeded since C# Dev Kit was running.

This is what I got a fresh windows sandbox with VS Code and C# DevKit installed. The install is denoted below in the console (I did not click anything besides to install CDK.) I wonder if we are doing something differently.
![image](https://github.com/microsoft/vscode-dotnettools/assets/23152278/3f6193ed-8f34-463e-8fc9-65815ffac55f)

**Comment by nagilson** [comment]
> Also IMO if C# Dev Kit asks for 8.0 and 8.0.6 is already installed, that should be plenty good enough to immediately return without a web call to make sure that's the lates

We can add a feature / option flag for that and I think it's a good idea, we can make an issue on our repo. I wouldnt change the default because there are prior partners who relied on us from a security perspective to keep runtimes up to date.

**Comment by AArnott** [comment]
Great. I'm glad the problem is understood now.

>  The install is denoted below in the console (I did not click anything besides to install CDK.) I wonder if we are doing something differently.

If you only print when you acquire .NET initially, it may be that installing C# Dev Kit actually activated the acquisition extension and triggered a download. I might have only been looking at the log after restarting VS Code.

**Comment by Monagle** [comment]
So is there any temporary work around for working offline before this fix is in? As others have said, shortening the timeout doesn't work and I tried also manually setting a shared dotnet path but this seems to be ignored. I often work without Internet access, so this is a significant hindrance.

**Comment by nagilson** [comment]
Fix for this is pending release of .NET Install Tool 2.1.2

**Comment by nagilson** [comment]
This should be fixed now. Please let us know if it's not.

**Comment by Flavelius** [comment]
If i understand correctly than i still have this issue. I'm on ubuntu 24, and when offline it takes quite some time until the dotnet acquisition error appears in the status bar. But when i set the shared existing dotnet path to in my case 
/home/myuser/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/9.0.4~x64/dotnet
where it downloaded it last time, it works just fine. If i understand correctly then it should check for the install path first with newer versions, it seems that doesn't fully work yet (atleast in my case).
It seems to check some path according to the logs, but ultimately doesn't use the existing download.
dotnet install tool 2.3.3

**Comment by nagilson** [comment]
That should be the case, but it might be that the other extension had a different version of .NET that it required (.net 8) that was not downloaded. Another possibility is that for some reason the install was corrupted, or it thought it was, so it didnt use it. I'd need a log /issue over at https://github.com/dotnet/vscode-dotnet-runtime to determine this (the new issue template has more info.)
