### ISSUE TITLE
Hot Reload not effective on .NET Web API template

### ISSUE THREAD

**Issue by PeterDraex** [microsoft/vscode-dotnettools#1034]
Type: <b>Bug</b>

1. Run `dotnet new webapi --use-controllers -o DebugHotReload` to create a new project
2. Open your File -> Preferences, make sure hot reload is enabled
3. Open WeatherForecastController.cs, add new method:
```csharp
        [HttpGet("TryThis")]
        public IActionResult TryThis()
        {
            return Ok("trythis");
        }
```
4. Start debugging using F5, use default C# debugging config.
5. Wait until the app starts. Open `/WeatherForecast/TryThis` in your browser
6. You should see `trythis`.
7. Change `[HttpGet("TryThis")]` to `[HttpGet("TryThis2")]` and rename the method to `TryThis2`.
8. Open `/WeatherForecast/TryThis2` in your browser
9. EXPECTED is that you see `trythis`. ACTUAL result is a 404 error.

Posting this here, because it works as expected in Visual Studio 2022 preview.

Extension version: 1.5.8
VS Code version: Code - Insiders 1.88.0-insider (46b756b8434730593b3c911fd1ca43366b29eb03, 2024-03-28T10:54:31.414Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (8.82GB free)|
|Process Argv|--crash-reporter-id 1c05e606-ec37-4823-bc38-c9bc58d9247a|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|15.49GB (12.95GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
8082a590:30961435
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
gee8j676:30988845
gd77d436:30999572

```

</details>

**Comment by claudiaregio** [comment]
@dbreshears why was this moved to not validated? Do we have a PR/fix for this yet?

**Comment by dbreshears** [comment]
@LittleLittleCloud mentioned this may be resolved and just needs validated

**Comment by claudiaregio** [comment]
@LittleLittleCloud Do we have PR for this? Could you update CDK board with it?

**Comment by LittleLittleCloud** [comment]
@claudiaregio 

It's because C#DK doesn't support restart on rude edit in 2024/03/28. The change this user made is a rude edit, in VS it can be recovered by rebuild and restart, but in C#DK it doesn't.

I think you can mark it resolved by #2133

**Comment by dbreshears** [comment]
@LittleLittleCloud, this still reproduces.   I have "[Experimental] Enables C# Hot Reload while debugging" enabled.

**Comment by LittleLittleCloud** [comment]
Can you share the hotreload logs from output? I've seen the following message

<img width="2015" height="693" alt="Image" src="https://github.com/user-attachments/assets/5daabad6-cb3e-4473-ac4e-64f6ea89064c" />


If I enable `HotReloadAutoRestart` to true, changing the HttpGet route name trigger a rebuild and restart

**Comment by claudiaregio** [comment]
@dbreshears Can you provide the above for @LittleLittleCloud ?

**Comment by dbreshears** [comment]
@LittleLittleCloud Here is the Hot Reload log, but you mentioned in last post enabling "HotReloadAutoRestart".  Where do you do that?  Project Property?

2025-10-23 19:24:40.479 [info]  💡 Possible code changes were found.
2025-10-23 19:24:43.515 [warning]  C:\samples\DebugHotReload\Controllers\WeatherForecastController.cs (line 1): error ENC1008: Changing source file 'C:\samples\DebugHotReload\Controllers\WeatherForecastController.cs' in a stale project has no effect until the project is rebuit.
2025-10-23 19:24:43.516 [info]  No code changes were found.
2025-10-23 19:24:58.638 [info]  No code changes were found.
2025-10-23 19:25:00.846 [info]  No code changes were found.

**Comment by claudiaregio** [comment]
@LittleLittleCloud could you follow up on this one? it's been rolled over as not validated

**Comment by LittleLittleCloud** [comment]
@dbreshears 

```
2025-10-23 19:24:43.515 [warning] C:\samples\DebugHotReload\Controllers\WeatherForecastController.cs (line 1): error ENC1008: Changing source file 'C:\samples\DebugHotReload\Controllers\WeatherForecastController.cs' in a stale project has no effect until the project is rebuit.
```

This warning is irrelevant to this bug. vscode, the warning should be disappeared if you clean the build artifacts and terminate all language server process and restart.

I've seen this warning sometimes when applying hotreload changes but I can't consistently reproduce it. We can create another tracking issue for this hotreload warning and collecting more information.
