### ISSUE TITLE
Debugger exits while stepping through code

### ISSUE THREAD

**Issue by mmiller-d8** [microsoft/vscode-dotnettools#1070]
Type: <b>Bug</b>

Almost every single time I try to step through code, the debugger just goes away.  I hit step-over and the highlighted line just goes away and the app stops responding to input.  

It can be on completely inoccuous lines of code.  There is no crash, no error message, nothing to indicate that anything is wrong.  It just stops.  Often it is after just one or two lines of code.

It's as if the debugger goes off waiting for the line of code to execute and never comes back.  Kind of like if you have an async method and you needed to use ConfigureAwait(false) but didn't.  Only this doesn't have to have an async method to happen.

Extension version: 0.10.61
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|96.00GB (4.46GB free)|
|Process Argv|--crash-reporter-id 1618046c-b005-4c1a-89ae-cb627902572c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
0ee40948:31013168

```

</details>

**Comment by sumowesley** [comment]
I don't know if this helps, but we upgraded our M1 Macbook Air system to .NET 8.0.204 yesterday. Since then, it would start a Maui app but the debug controls would disappear and we never hit a breakpoint. Reverting to .NET 8.0.104 has brought back the debugger controls and the breakpoints work.

VS Code: 1.88.1
.NET MAUI extension: 0.11.16
macOS: Sonoma 14/4/1
Chip: Apple M1

**Comment by sumowesley** [comment]
Hi @mauroa,

When we tried it last week, the debugger didn't work on a brand new Maui project or our main development here.

I've just swapped .net directories to revert to 8.0.204.

**Dotnet:**
- v8.0.204

**Extensions:**
- .NET MAUI  v0.11.16
- C# dev kit v1.5.14
- C# v2.26.13

The new MAUI project from last week works with VSDbg. However, our larger project does not work with VSDbg; it does work when I disable VSDbg from the extension settings.

Let me know if you need any more.

**Comment by mmiller-d8** [comment]
@mauroa 

I checked mine, and it was already checked.  I unchecked it and was able to step through code as I could before.  When I checked it again, I was able to step through a lot more lines of code (a dozen or more) before it showed the same behavior - the debugger function stopping and the app not responding to input.

**Comment by mauroa** [comment]
@sumowesley @mmiller-d8 any chance you can privately share your projects? That would help identifying what could be making the debugger to fail at some point. Thanks

**Comment by sumowesley** [comment]
@mauroa, I've added you to the relevant repository. The MAUI project is MossUI.

**Comment by mmiller-d8** [comment]
If you don't mind, I'd like to wait to see if you can reproduce it with the one.  Mine isn't quite in a state where you can run it at the moment.  Not without deploying the API locally.  If you can't repro it with his, I'll deploy my API to azure and give you a branch that's pointed at it.

**Comment by sumowesley** [comment]
Hi there, are there any changes I need to make to get this working with the new debugger?

**Comment by mmiller-d8** [comment]
So, is debugging just not a feature for .net Maui anymore?  Debugging is on the backlog indefinitely?

@mauroa @AllenD-MSFT @WardenGnaw

**Comment by mauroa** [comment]
Resolved in latest C# pre-release version

**Comment by mofdaddy** [comment]
Hi @mauroa 
> Resolved in latest C# pre-release version

Is this C# Dev Kit and/or .NET MAUI extensions, and is it supposed to be out now?
I tried switching both to prerelease, but this problem persists.

I also commented here: https://github.com/microsoft/vscode-dotnettools/issues/1757
