### ISSUE TITLE
[BUG] iOS MAUI App Locks up when debugging on MacOS VSCode

### ISSUE THREAD

**Issue by tpitman** [microsoft/vscode-dotnettools#1526]
### Describe the Issue

When I debug my iOS MAUI app on MacOS using VSCode and the MAUI plugin it just locks up at random times.

Sometimes it will just be running fine and then stops responding. I don't get any exceptions or errors of any kind. It just stops working at all and I have to force close it.

This always happens right after hitting a breakpoint and then hitting RUN to continue debugging.

Again there are not exceptions or errors of any kind. I even opened the Mac console and attached to the phone and didn't see anything there either that would indicate anything.

This has been happening since version 8.0.20 since I have been using VSCode. I never had this issue with Visual Studio 2022 for Mac.

### Steps To Reproduce

1. Debug my app
2. Hit a breakpoint
3. Hit run
4. Notice the app doesn't respond anymore

### Expected Behavior

Not lock up

### Environment Information

- OS: MacOS Sonoma
- MAUI: net8.0, workload 8.0.82/8.0.100, SDK 8.0.400
- VSCode: 1.94.1
- MAUI VSCode Extension: 1.4.34 (pre-release) Also tried the release version 1.3.29 with the same results

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2241733">2241733</a>

**Comment by tpitman** [comment]
I just have to add a comment that I wish the VSCode experience was at least as good as VS for Mac.

I am trying to debug my app and now I have to delete my app and debug. Then it will work about 1/3 times. The other 2 times it starts debugging and then just says that the process has ended.

I then have to remove the app and it will debug 1/3 times.

Also just after removing the app and debugging this way a message appears asking if I want to allow this app to discover network devices. I always allow.

Sometimes ones it works I can debug until I disconnect the iPhone to head home from the office. Then I have to do the whole song and dance again the next time I get back to work until it works and then might work for a while.

I keep a lot of data in preferences, so having to remove the app causes me to start all over in setting things up to get back to the point to debug what I am working on. It is a real pain.

For all of this I went back to VS for Mac because I can't put up with all this hassle and need to get this bug figure out I am working on.

VS for Mac just works. It always debugs and I never have to remove my app to get back to debugging. I know I won't be able to use VS for Mac for many more days, so I just don't know what to do.

VS for Windows in a VM isn't any better. In fact everything about that is slower and more of a hassle.

Why can't the VSCode debugging work just like VS for Mac?

**Comment by mlancione** [comment]
I am also experiencing the same issues. Running VS Code on Mac w/ .NET 9 RC 2 using the iOS Simulator or an iOS device.

**Comment by mlancione** [comment]
Here are some outputs I see when the debugger issues occur.

When using “Step Over”:
```
Received a single step request while the previous one was still active.
Step request failed: This request is not supported by the protocol version implemented by the debuggee.
```

When using “Jump To Cursor”:
`Error setting next statement. Previous set next statement request is still in progress.
`

When using “Set Value” in Watch when on a breakpoint then hitting Run:
`Error setting next statement. Previous set next statement request is still in progress.
`

**Comment by prollin** [comment]
For those having issues debugging on device:

- Make sure your app has local network permission and *relaunch* the debugging session after granting it (either through the popup or in iOS settings if you denied by mistake). This only needs to be done after deploying the app for the first time. This is because VSCode uses TCP instead of USB for the debugging session and by the time the prompt show, it is too late for it to work. There is an already [an issue filed](https://github.com/microsoft/vscode-dotnettools/issues/1081) for supporting USB debugging. Would love for this to get prioritized as the caveat below makes this negative experience slightly worse.

- On caveat is that on iOS 18+ there seem to be a bug with how the OS show the local network permission prompt. In that case, having `NSLocalNetworkUsageDescription` in your `info.plist` should ensure that the prompt is presented when the debugger connects to the device (you'll still have to start the session again to be able to debug and hit breakpoints). If your app doesn't actually need that permission, I suggest to simply have it declared for your debug configuration. Read more about this apparent bug on[ apple's developer forum](https://forums.developer.apple.com/forums/thread/766133)

Hope this helps a few. Happy debugging!

**Comment by AllenD-MSFT** [comment]
I've removed the Nov2024 milestone since it is now unclear exactly when we will get this addressed. It is an active bug, and I expect it to be worked on with high priority, but it isn't a simple issue, so I didn't want to set up false expectations.

**Comment by mauroa** [comment]
This has been already resolved and the fix is available by updating the C# extension to latest pre-release. Thanks

**Comment by dingxiaolong** [comment]
Still have this debug issue on my side  ,even use all the extension with preview.     Not clear why it happens .

**Comment by bnSonic** [comment]
Interesting and thank you all for this issue-track! 

I was searching for that problem and found this one here.

**My problem is very similar or identical:**
I run my App with debugger on an iOS 18 Simulator (Xcode 16.3)
The App starts running normal - until suddenly it just stops responding. 
- No exception anywhere I look
- It just stops responding, you cannot click or scroll anything and I don't see any new entries on the debug console

It feels like a dead-lock on the main-thread or something.

If I hit the Pause-Button in the debugger, I'm staying at the Main.cs (in the iOS project) on this line
`UIApplication.Main(args, null, typeof(AppDelegate));`

so nothing helpful here too 


**What I'm looking for**
Sure, a final solution for that problem would be good ;) 

BUT: If there is ANY workaround for this, I would be happy too! Because it's very hard (and close to impossible) to develop the App in this way… because
- To fix UI Problems it's helpful to have the App running, reflecting any UI Changes live

But even harder:
- To find problems in my code I need to use the app and set break-points in different places to search for the bugs … but if the app stops after some seconds or after 2 minutes or so, I'm a) unable to reproduce my bug and b) always in doubt if this is a problem on my side anywhere in some Task or if it's a VSCode/C#/Debugger problem … 

I then have to run the App without debugger (on the same simulator) to see if it will hang too … and because this happens very soon but at a random time span from 30 seconds to maybe 5 minutes, it's VERY annoying to test this … 

Currently the App never hangs outside the debugger. Running on the iOS 18 simulator seems just fine. So I'm pretty sure there is some problem with the debugger

**I desperately seeking for a workaround, some setting or switch or "best practices" to avoid this hanging** 


**My Hardware / Software:**

- I'm on a Mac (MacBook Air M4 with macOS Sequoia 15.4.1

- I'm using VSCode:
Version: 1.99.3 (Universal)
Commit: 17baf841131aa23349f217ca7c570c76ee87b957
Date: 2025-04-15T23:18:46.076Z
Electron: 34.3.2
ElectronBuildId: 11161073
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.4.0

the Extensions are:
C# 
Version
2.72.34
Last Updated
2025-04-25, 14:33:00

C# Devkit
Version
1.18.25
Last Updated
2025-04-25, 14:33:00

.NET MAUI
Version
1.9.21
Last Updated
2025-04-25, 14:33:00

.NET install Tool
Version
2.3.3
Last Updated
2025-04-25, 14:33:00

**Comment by mikhail-yevstratiev** [comment]
@bnSonic hey there,
I was had the same problem when I've found this thread. The comments helped me to resolve the issue. 

What I did was:
1. Switch the C# extension to the latest pre-release version (currently 2.74.24)
2. Delete all obj and bin folders in project directory
3. Restart VSCode

After doing this iOS MAUI app doesn't freeze in simulator. Hope it helps.

**Comment by dingxiaolong** [comment]
> [@bnSonic](https://github.com/bnSonic) hey there, I had the same problem when I found this thread. The comments helped me to resolve the issue.
> 
> What I did was:
> 
> 1. Switch the C# extension to the latest pre-release version (currently 2.74.24)
> 2. Delete all obj and bin folders in project directory
> 3. Restart VSCode
> 
> After doing this iOS MAUI app doesn't freeze in simulator. Hope it helps.

Not works for me  ,still have the Freeze issue .
