### ISSUE TITLE
[BUG] Testing with "Testing Platform Protocol" option hangs when debugging

### ISSUE THREAD

**Issue by erwinkramer** [microsoft/vscode-dotnettools#1616]
### Describe the Issue

Testing with the (experimental) Testing Platform Protocol option (`dotnet.testWindow.useTestingPlatformProtocol`) will not start when debugging.

I'm using [TUnit](https://thomhurst.github.io/TUnit/docs/tutorial-basics/running-your-tests#vs-code).

I can confirm it does work well with the similar option enabled on `Microsoft Visual Studio Community 2022 (64-bit) - Preview`, so it seems an isolated issue to the C# Dev Kit extension. 

Reference to the issue on the TUnit project: https://github.com/thomhurst/TUnit/issues/1246

### Steps To Reproduce

1. Clone this repo: https://github.com/erwinkramer/bank-api?tab=readme-ov-file#bank-api
2. Observe the tests: https://github.com/erwinkramer/bank-api/blob/main/bank-api-minimal-unittests/Api.Test.cs
3. Run the tests in debug mode, so click: `Debug Test`. 

### Expected Behavior

1. Should start and run the tests
2. Should be able to cancel them

### Environment Information

- OS: WIndows 11
- VSCode version: 1.95.3
- Extension version: 
   - C# Dev Kit: v1.14.2 (pre-release) and v1.13.9
   - C#: v2.55.29

**Comment by ocallesp** [comment]
Hi @fhnaseer, this issue seems to be related to TestPlatform. Could you take a look and handle it?

**Comment by lbrecheisen** [comment]
Ran into this today when trying out TUnit. Looks to still be an issue.

**Comment by rschili** [comment]
If it helps, I found that the tests do not execute at all when started like that. But vscode seems to spin and wait for them to attach.
Works fine in Visual Studio or when just doing "Run Tests".

**Comment by fhnaseer** [comment]
> If it helps, I found that the tests do not execute at all when started like that. But vscode seems to spin and wait for them to attach. Works fine in Visual Studio or when just doing "Run Tests".

@ocallesp It seems like there is a bug in VSCode integration. Please have a look.

**Comment by thomhurst** [comment]
Is there any update on this?

**Comment by ocallesp** [comment]
@thomhurst 

WIP a discussion with the TestPlatform team about this error:

```
========== Starting test run ==========
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudio.TestWindow.VSCode.Service.TestWindowCallbackService.LaunchDebugTestHostAsync(LaunchTestHostRequest launchRequest, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallWithCatchAsync[T](IInternalLogger log, Func`1 func, T defaultValue)
System.ArgumentException: Process with an Id of -1 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at Microsoft.VisualStudio.TestWindow.Internal.RemoteAgent.TestingPlatform.Providers.ClientServerProfileBase.StartProcessWithDebuggerAsync(TestingPlatformLaunchConfig config)

```

**Comment by ocallesp** [comment]
The `LaunchDebugTestHostAsync `implementation is missing for VSCode because it was assumed that TestPlatform would handle it. However, it is required for this scenario.

I am currently working on implementing LaunchDebugTestHostAsync for VSCode

cc: @drognanar

**Comment by ocallesp** [comment]
@erwinkramer The fix has been implemented and may be included in the next release. Please close this ticket once verification is complete.

**Comment by ocallesp** [comment]
To verify that you're using the C# Dev Kit version with the fix, enable diagnostic verbose logging for Test Explorer and ensure that the "Test Explorer version" is 7 or higher.

`[diag] Test Explorer version: 7`

**Comment by erwinkramer** [comment]
@ocallesp so in some future release, or just the first next C# Dev Kit release?

**Comment by scominoekd** [comment]
Which version of C# Dev Kit will include the fix? I got the latest prerelease 1.17.12 and I have Test Explorer version: 4.

<img width="704" alt="Image" src="https://github.com/user-attachments/assets/d463f80a-ffba-4493-85a5-dc2cf0d8e54c" />

**Comment by ocallesp** [comment]
@erwinkramer the next release will be March 4th with v1.17

**Comment by ocallesp** [comment]
These fixes should be included in pre-release version v1.17.48.

**Comment by WolfBublitz** [comment]
Hallo,

I have just tried with the latest pre-release version of the Dev-Kit 1.17.48, but debugging still does not work.

![Image](https://github.com/user-attachments/assets/683c2b94-6e85-4ea5-9a7f-48d129f27463)

As you can see, the debugger will not connect.

**Comment by WolfBublitz** [comment]
I have just checked it with Windows there it works, with the message @thomhurst  mentioned. With Linux it does not connect 👎.

**Comment by ocallesp** [comment]
@WolfBublitz On Linux, does the debugger fail to attach, or does it display a connection issue while still functioning correctly?

**Comment by WolfBublitz** [comment]
It as shown on the screenshot. It starts waiting for connection. No further error is indicated.

**Comment by dmcbride** [comment]
Can confirm that, on Linux, it fails to connect to the debugger. As far as I can tell, the socket it's using should be visible just fine, but maybe the debugee is running in some sort of protected mode that prevents it from accessing `/tmp`?

**Comment by ocallesp** [comment]
Removing the 'fixed-pending-release' label as the bug is still present on Linux.

**Comment by WolfBublitz** [comment]
I have tested the latest preview version of the Dev-Kit (1.17.62). The issue was not solved, but now I get this error message:

Failed to attach to process: Unknown Error: 0x80131c08

**Comment by WolfBublitz** [comment]
Just checked with Dev-Kit 1.18.16 (released today), still not working.

`Unable to start debugging. Failed to attach to process: Unknown Error: 0x80131c08
`

**Comment by BramMusters** [comment]
I have the issue as well on a Mac.

**Comment by JamesFieldist** [comment]
Same here on mac.

**Comment by AbhitejJohn** [comment]
@ocallesp : There's an increasing number of reports on this issue, so I've marked this as a high-priority. This also affects aspire test debugging - so this repo is a great repro: https://github.com/dotnet/aspire . I'm wondering if the debug adapter logic we have [here](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VSUnitTesting?path=/src/VSCode/Client/src/TestWindowVSCodeServerCallbackService.ts&version=GBmain&line=67&lineEnd=84&lineStartColumn=3&lineEndColumn=4&lineStyle=plain&_a=contents) is accurate for non-windows environments. Tagging @WardenGnaw for thoughts on that.

**Comment by WolfBublitz** [comment]
Still no luck with Dev-Kit 1.19.20 :-(.

**Comment by WolfBublitz** [comment]
Good to hear that is now fixed, can you say which release will provide the fix?

**Comment by dmcbride** [comment]
Still no luck with dev-kit 1.19.35, hopefully it missed that cutoff and we'll see it soon.

**Comment by dmcbride** [comment]
This appears to work for me now with 1.19.45 on Linux.

**Comment by erwinkramer** [comment]
@dmcbride can confirm for the same `1.19.45` but on Windows, working great!

**Comment by WolfBublitz** [comment]
I can confirm that 1.19.45 works on Linux now. Thanks for fixing!

**Comment by scominoekd** [comment]
Working on macOS too. Thanks!
