### ISSUE TITLE
[BUG] Unit Tests are not discovered in Test Explorer by C# Dev Kit in version 1.10.16 to 1.13.9 inclusive

### ISSUE THREAD

**Issue by danbailey1000** [microsoft/vscode-dotnettools#1644]
### Describe the Issue

Unit tests are not discovered by Test Explorer  by  C# Dev Kit version 1.10.16 to 1.13.9 inclusive 

I have tried it with a very simple project with one unit test and the Test Explorer says "no tests have been found in this workspace yet". 

namespace TestProject1;

namespace TestProject1;

```
[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
        Assert.IsTrue(true);
    }
}
```

Test Explorer works in extension version 1.9.55. All tests are discovered correctly with exactly the same project. I tested all versions and 1.9.55 worked. 

### Steps To Reproduce

In a windows 11 environment when opening a workspace with the attached project Test Explorer does not discover any tests[dantest.zip](https://github.com/user-attachments/files/17945045/dantest.zip)

### Expected Behavior

The test explorer should automatically discover unit tests 

It works in extension version 1.9.55. All tests are discovered correctly 

### Environment Information

Windows 11 
VS Code version 1.95.3
Extension version 1.10.16 to 1.13.9 inclusive

**Comment by panbohaha** [comment]
there is the some issue for me.

**Comment by ocallesp** [comment]
@danbailey1000 

I was unable to reproduce the issue.

In your case, was the build completed successfully?

- If yes, could you share the output from the C# Dev Kit - Test Explorer?
- If no, that might be the root cause of the issue.

**Comment by danbailey1000** [comment]
@ocallesp 
thanks for looking

The build is completed successfully. I tried this many times. dotnet build and also via the test explorer refresh button. 

The only output from test explorer is that it did not discover any tests. 

My guess this is some environmental issue on my primary laptop in combination with a defect. Something must have changed in C# Dev because the older version 1.9.55 works fine but as soon as I update the tests are not discovered.  (I also did not reproduce on another computer).  Perhaps the history of changes since 1.9.55 would reveal something suspicious. I see there have been fixes in the test explorer areas and perhaps on of these fixes caused the problem I am seeing.  If you want to screenshare can also arrange something.

**Comment by ocallesp** [comment]
In the output C# Dev Kit - Test Explorer, do you see if SDK was resolved ? does it show if any project added ?

**Comment by tysonstewart** [comment]
I came looking for an issue to track the status and perhaps this one is it. I've been using this extension for perhaps 5 months or so and it never picks up a single test in a file. I always need to add at least one more test for them to show up in Test Explorer. Additionally, I've found that tests I add at the top of the file after I've already added a few do not show up without reloading the window.

I was previously on .NET 7 but recently updated to 8 and it has remained true. I am using a dev container based on `dotnet:8.0-bookworm-slim` and my machine is Mac if any of those things should be a factor.

**Comment by joaoopereira** [comment]
I had this issue today, and I did this steps to make it work:
1. Close vscode
2. Delete the content of `C:\Users\[UserName]\AppData\Roaming\Code\User\workspaceStorage`
3. Open vscode
4. Click on Test Explorer - Refresh Tests

**Comment by ocallesp** [comment]
@joaoopereira, do you have any steps to reproduce the issue, or could you share the output from the C# DevKit - Test Explorer? Also, I noticed the original issue was reported on Windows—are you encountering the same scenario now?

**Comment by ocallesp** [comment]
@danbailey1000 have you tried deleting the bin\ and obj\ folders in your repro project [dantest.zip](https://github.com/user-attachments/files/17945045/dantest.zip) and rebuilding it ? Does that resolve the issue ?

**Comment by gregorybleiker** [comment]
I have this with the latest versions as well. Diagnostics settings is not giving me anything. Clean lib test project created according to ms [docs](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test).  Going back to 1.8 version of plugin helps.

**Comment by ocallesp** [comment]
@gregorybleiker are you encountering this issue in xUnit or MSTest?

**Comment by gregorybleiker** [comment]
@ocallesp both

**Comment by gregorybleiker** [comment]
Windows 10

**Comment by ocallesp** [comment]
In this thread, no logs have been posted yet, so I am trying to reproduce the original bug.

Could someone confirm if the logs you are seeing are similar to this:

```
Created Test Controller
Log verbosity: minimal
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\9.0.102].
Initialized Test Explorer Server [2600]
Test Store Folder: c:\Users\MyUser\AppData\Roaming\Code\User\workspaceStorage\0ca27759c40293c96da27a69851c1238\ms-dotnettools.csdevkit
Test data store opened in 0.025 sec.
Initialized project system provider.
```


instead of

```
Created Test Controller
Log verbosity: minimal
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\9.0.102].
Initialized Test Explorer Server [4632]
Test Store Folder: c:\Users\MyUser\AppData\Roaming\Code\User\workspaceStorage\0ca27759c40293c96da27a69851c1238\ms-dotnettools.csdevkit
Test data store opened in 0.057 sec.
Initialized project system provider.
1 projects added, 0 changed, 0 removed.
Scheduling discovery: C:\Users\MyUser\source\repos\dantest\dantest\TestProject1\bin\Debug\net8.0\TestProject1.dll [Last modified: 1/27/2025, 7:46:42 PM]
========== Starting test discovery ==========
========== Test discovery finished: 1 Tests found in 1 sec ==========
1 tests discovered from C:\Users\MyUser\source\repos\dantest\dantest\TestProject1\bin\Debug\net8.0\TestProject1.dll in 1023.4345 ms
```

In the bad scenario, it seems the logs are missing this line:
`1 projects added, 0 changed, 0 removed.`

If this matches your experience, it would suggest the issue occurs when no DLLs are generated from builds- specifically, when VS Code is opening the folder for the first time. 


Could someone confirm if this is the case?

**Comment by gregorybleiker** [comment]
@ocallesp this is the output of the logs:
```
Created Test Controller
Log verbosity: diagnostic
[diag] C# Dev Kit version: 1.15.34
[diag] platform: win32 arch: x64
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\9.0.102].
Initialized Test Explorer Server [41896]
Test Store Folder: c:\tools\vscode\data\user-data\User\workspaceStorage\544d7c1be2c78fefc8d9358298eb5a0b\ms-dotnettools.csdevkit
Test data store opened in 0.010 sec.
[diag] Test Store loaded from persistance: No
Initialized project system provider.
```

**Comment by gregorybleiker** [comment]
I have also pushed the repo I'm using to test: https://github.com/gregorybleiker/dotnet-unit-testing/

**Comment by gregorybleiker** [comment]
@ocallesp additional things that might be perculiar about my environment: 
- we have company wide windows firewall settings (via GPO)
- we are behind a proxy that is known to cause problems with certificates

**Comment by ocallesp** [comment]
Fixed. Available in the next release.

**Comment by codingsteff** [comment]
After build/rebuild of my devcontainer, no tests are displayed or recognized.

Here is my log:
```
Created Test Controller
Log verbosity: minimal
Checking environment variable 'DOTNET_HOST_PATH': Current value = '<null>', Proposed value = '/usr/share/dotnet/dotnet'
Updated environment variable 'DOTNET_HOST_PATH' to '/usr/share/dotnet/dotnet' (was '<null>', invalid or missing)
Initialized Test Explorer Server [872]
Using vstest from dotnet sdk in [/usr/share/dotnet/sdk/9.0.203].
Test Store Folder: /home/vscode/.vscode-server/data/User/workspaceStorage/1c383dc2d5e302842875c7a53abe8ce9/ms-dotnettools.csdevkit
Test data store opened in 0.087 sec.
Test controller initialized.
Initialized project system provider.
Waiting for projects to be detected by Project System...
```

When I click on Refresh Tests, there is an entry in the log every time:
```
No runSettingsPath configured. Falling back to default settings.
```
With `dotnet build` or `dotnet test` there is no change in the log.



After closing and reopening they are immediately available:
```
Created Test Controller
Log verbosity: minimal
Checking environment variable 'DOTNET_HOST_PATH': Current value = '<null>', Proposed value = '/usr/share/dotnet/dotnet'
Initialized Test Explorer Server [8113]
Updated environment variable 'DOTNET_HOST_PATH' to '/usr/share/dotnet/dotnet' (was '<null>', invalid or missing)
Using vstest from dotnet sdk in [/usr/share/dotnet/sdk/9.0.203].
Test Store Folder: /home/vscode/.vscode-server/data/User/workspaceStorage/1c383dc2d5e302842875c7a53abe8ce9/ms-dotnettools.csdevkit
Test data store opened in 0.020 sec.
Test controller initialized.
Initialized project system provider.
Waiting for projects to be detected by Project System...
1 projects added, 0 changed, 0 removed.
Scheduling discovery: /bookify/test/Bookify.Domain.UnitTests/bin/Debug/net9.0/Bookify.Domain.UnitTests.dll [Last modified: 4/12/2025, 6:34:10 AM]
No runSettingsPath configured. Falling back to default settings.
========== Starting test discovery ==========
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v3.0.2+dd36e86129 (64-bit .NET 9.0.4)
[xUnit.net 00:00:00.24]   Discovering: Bookify.Domain.UnitTests
[xUnit.net 00:00:00.50]   Discovered:  Bookify.Domain.UnitTests
========== Test discovery finished: 1 Tests found in 1.4 sec ==========
1 tests discovered from /bookify/test/Bookify.Domain.UnitTests/bin/Debug/net9.0/Bookify.Domain.UnitTests.dll in 1407.0648 ms
```

**Comment by daniel-sullivan** [comment]
This issue is still affecting us with the exact same env. and behaviour as @codingsteff

Should we open a new issue or can this issue be reopened?
