### ISSUE TITLE
[BUG] Running Tests with Code Coverage results in passing tests, but Test Coverage is all 0.00%

### ISSUE THREAD

**Issue by Clink50** [microsoft/vscode-dotnettools#1779]
### Describe the Issue

Upon clicking "Run Tests with Coverage" in the Test Explorer, the tests are passing no problem, but the code coverage in the Test Coverage window displays all 0.00%. 

I checked the C# Dev Kit - Code Coverage logs and see that a log `CodeCoverage: Report generated: %APPDATA%\Local\Temp\1017642997`. The file cannot be read by the Test Explorer. Looking at #554, I ran `dotnet test --collect "XPlat Code Coverage"` and the code coverage files were generated in each Unit Test project at `.../TestsResults/{GUID}/coverage.cobertura.xml`. Then according to the [documentation](https://code.visualstudio.com/docs/csharp/testing#:~:text=and%20search%20for%20%22-,Test%3A%20Show%20Coverage,-%22%20to%20access%20the), I chose one of the `coverage.cobertura.xml` files, and it displayed the code coverage information correctly. 

Created a working repository [here](https://github.com/Clink50/TestProject.Api). I ran this in Codespaces, and it showing the test coverage as expected. Here is the log that was generated when running the test there in the C# Dev Kit - Code Coverage output window:
`Created Coverage Controller`
`CodeCoverage: Report generated: /tmp/275277561`

### Steps To Reproduce

1. Pull down the reproduction repo [here](https://github.com/Clink50/TestProject.Api).
2. Build the project
3. Run the tests with coverage via the Testing extension from C# Dev Kit.
4. Observe in the test explorer that it's showing all 0.00% instead of 100%

### Expected Behavior

When running the Test with Coverage, I should see the correct test coverage showing in the Test Coverage window.

### Environment Information

- OS: Windows 11
- VS Code Version: 1.96.3
- C# Dev Kit Version: 1.16.6

**Comment by ocallesp** [comment]
Assigning this issue to the TestPlatform team for an initial review, as it relates to Test Coverage.

**Comment by fhnaseer** [comment]
@Clink50 I tried to repro this using your repo. However, I am seeing coverage results correctly.

![Image](https://github.com/user-attachments/assets/bf7d862c-e316-4982-96ca-4e624cd1f3fc)

C# Dev Kit Version: 1.17.12
VSCode Version: 1.98.0-insider (system setup)

Can you please use latest C# DevKit and try again?

**Comment by Clink50** [comment]
@fhnaseer - Okay I'm running this on a company machine, so is it possible it could be a firewall or permissions issue? I wouldn't think so, but wanted to ask. 

It wouldn't let me add the file generated from the Code Coverage report in the App Data most likely because it doesn't have an extension. I added `.txt` to the end of the generated file. I don't think it changed the encoding of the file.

Image below is from company computer running the tests.

C# Dev Kit Version: 1.16.6
VSCode Version: 1.96.3 (system setup)

![Image](https://github.com/user-attachments/assets/3438e339-0fab-4af4-a559-d997f8eebaf7)
Code Coverage Generated: [2102811337.txt](https://github.com/user-attachments/files/18870572/2102811337.txt)

Image below is from my home computer running the tests. 

C# Dev Kit Version: 1.17.12
VSCode Version: 1.98.0-insider (user setup)

![Image](https://github.com/user-attachments/assets/ed3ea108-d75b-4e50-9775-ae6f68c57887)
Code Coverage Generated: [14433608.txt](https://github.com/user-attachments/files/18870574/14433608.txt)

Looks like the main differences here are the new versions. I will have to wait until the newest version of C# Dev Kit is released to test and see if that fixes the issue.

**Comment by fhnaseer** [comment]
Coverage file seems fine. I opened it in Visual Studio, and it is reporting coverage properly.
![Image](https://github.com/user-attachments/assets/5272d478-7748-4822-bea4-e477e67a90ab)

Can you open coverage report 2102811337.txt in vscode directly?
![Image](https://github.com/user-attachments/assets/ceb97220-0ef2-4dd5-9705-f8d4eb4e1d13)

**Comment by AbhitejJohn** [comment]
@Clink50 : Gently pinging back on @fhnaseer query above.

**Comment by nwfortnerfv** [comment]
Has there been any movement on this?

**Comment by fhnaseer** [comment]
@nwfortnerfv we were not able to reproduce this. If you are able to reproduce this then please let us know.

**Comment by MaikMaster5** [comment]
I ran into the same behaviour here today as I wanted to check my coverage.
It was all 0% on my work laptop, but then I got confused when it was 0% on my personal laptop as well, which intrigued me as that was different to [Clink50's behaviour](https://github.com/microsoft/vscode-dotnettools/issues/1779#issuecomment-2668974724).

One thing I realized that's consistent between my work and personal laptop is that they're both running in system mode (Administrator) and not user mode.
I started vscode up without Administrator permissions and reran the tests again, with the tests now showing the coverage!

Is everyone here **running VSCode with elevated permissions**? I fear that might be the cause of these issues.

**Comment by MaikMaster5** [comment]
Any different behaviour if you run it without administrator permissions?

**Comment by gabriellamounier-kneat** [comment]
I've got the same issue.

Code coverage was working perfectly, after a couple of vscode updates, coverage is displaying as 0.00%.

vscode: 1.103.1 (windows 11)
C# dev kit: 1.41.11

I don't think it's generating the coverage reports, as couldn't find any message. 

I also noted a difference in the output window: 

Currently it's displaying "Close test coverage"

<img width="286" height="84" alt="Image" src="https://github.com/user-attachments/assets/1aac71af-d4c3-47d1-9976-9e21bf730adb" />

But before it was "View test coverage"

<img width="321" height="131" alt="Image" src="https://github.com/user-attachments/assets/ebc709fe-dcb0-4144-9e6e-d2babf94327e" />

**Comment by bluemodus-mwills** [comment]
I have the same issue. "Test coverage" was reporting 0% in "C# Dev kit" but not in Visual Studio Enterprise test coverage reports.

vscode: 1.103.1 (windows 11)
C# dev kit: 1.41.11

VSCode was running with Administrator privileges. 

After, restarting VSCode with non-Administrator privileges, C# Dev Kit code coverage reporting worked -- 93%.

**Comment by gabriellamounier-kneat** [comment]
I can confirm that, when vscode (C# dev kit) is invoked from an unprivileged command prompt, code coverage is displayed as  expected.

<img width="259" height="257" alt="Image" src="https://github.com/user-attachments/assets/1c510aa4-fc1a-4bdf-83b2-23fef8f1f93c" />

When it's invoked from an elevated command prompt, it displays as 0%

<img width="260" height="274" alt="Image" src="https://github.com/user-attachments/assets/c727c04c-5c57-45fb-ad2d-ef0ce93e6776" />

**Comment by jbrockerville** [comment]
Same issue. My login account is admin. I found that I could launch vscode "de-elevated" from *Process Explorer* with `File -> Run as Limited User`. That instance shows the coverage as expected.

**Comment by julioct** [comment]
I noticed the exact same issue today.

**VS Code opened as Admin**

<img width="1536" height="1024" alt="Image" src="https://github.com/user-attachments/assets/c865d50c-a50d-4e64-bf5e-fbfb624e1299" />

**VS Code opened normally**

<img width="1536" height="1017" alt="Image" src="https://github.com/user-attachments/assets/9f2edfab-83ad-45b5-8597-097c6b14f705" />

Both are the exact same code base.

Why can't the Admin one get any code coverage numbers?

**Comment by hammad-awan** [comment]
Please fix this bug. It seems silly that this does not work in a higher privileged mode.

**Comment by fhnaseer** [comment]
This has been fixed and will be available in the upcoming release.

**Comment by hammad-awan** [comment]
In what release is this supposed to be fixed? The extension has been updated multiple times but the issue still persists.

**Comment by marianomontano** [comment]
running on windows 11
VS Code version: 1.117.0
C# Dev Kit version: 3.20.199

The issue is not reproducible anymore.

<img width="401" height="301" alt="Image" src="https://github.com/user-attachments/assets/50e7dc8f-7c66-4d18-9cb4-f96232b3eeaf" />
