### ISSUE TITLE
Intellisense and syntrax highlighting intermittent when C# Dev Kit is installed

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#210]
From vscode-csharp created by [jesperkristensen](https://github.com/jesperkristensen): dotnet/vscode-csharp#5853  

Type: <b>Bug</b>

After installing the new C# Dev Kit extension, the intellisense, go to definition and syntax highlighting is very intermittent, often only working for types defined in my own project, but not types defined by nuget packages or the framework.

![image](https://github.com/dotnet/vscode-csharp/assets/548890/59dfe156-78e4-4692-ba99-4ceee39f1813)

It seems related to issue #5849 to me, but sine it was asked there to file new issues, I am filing a new one.

<details>
<summary>Dotnet Server Trace log</summary>
[LanguageServerHost]workspace/diagnostic - Canceled
[LanguageServerHost][08:09:06.678][End]workspace/diagnostic
[LanguageServerHost]Shutting down
[Info  - 10.09.06] Shutting down
Dotnet path: c:\Users\Administrator\.vscode-server\data\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.8\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Starting server at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.exe
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\Administrator\.vscode-server\extensions\ms-dotnettools.csharp-2.0.238-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
info: LanguageServerHost[0]
      Starting server...
[LanguageServerHost][08:09:07.907][Start]initialize
[LanguageServerHost][08:09:07.925][Start]Initialize
[LanguageServerHost][08:09:07.989][End]Initialize
[LanguageServerHost][08:09:08.009][End]initialize
[LanguageServerHost][08:09:08.013][Start]initialized
[LanguageServerHost][08:09:08.091][End]initialized
[LanguageServerHost][08:09:08.093][Start]serviceBroker/connect
[LanguageServerHost][08:09:08.093][Start]textDocument/didOpen
[LanguageServerHost]didOpen for file:///c:/home/tester/TesterProj/Program.cs
[LanguageServerHost][08:09:08.102][End]textDocument/didOpen
[BrokeredServiceTraceListener]ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener]SameProcess proffered brokered service(s): Microsoft.VisualStudio.RemoteBrokeredServiceManifest (0.2).
[BrokeredServiceTraceListener]ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener]SameProcess proffered brokered service(s): Microsoft.VisualStudio.GlobalBrokeredServiceContainer.MissingServiceDiagnostics (1.0).
[BrokeredServiceTraceListener]ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener]SameProcess proffered brokered service(s): Microsoft.ServiceHub.Framework.AuthorizationService.
[LanguageServerHost]Could not find 'file:///c:/home/tester/TesterProj/Program.cs'.  Searched Host
[BrokeredServiceTraceListener]ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener]SameProcess proffered brokered service(s): Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1), Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService, Microsoft.CodeAnalysis.LanguageServer.IHelloWorld (0.1).
[Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.BrokeredServiceBridgeProvider]Setting up brokered service bridge
[BrokeredServiceTraceListener]ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener]Requesting proxy to "helloServiceHubDotNetHost (0.1)"
[BrokeredServiceTraceListener]ServiceBroker Warning: 3 : 
[BrokeredServiceTraceListener]Brokered service "helloServiceHubDotNetHost (0.1)" has no proffering source and no package registered to load.
[BrokeredServiceTraceListener]ServiceBroker Warning: 2 : 
[BrokeredServiceTraceListener]Request for proxy to "helloServiceHubDotNetHost (0.1)" is declined: ServiceFactoryNotProffered.
[BrokeredServiceTraceListener]ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener]Requesting proxy to "helloServiceHubDotNetHost (0.1)"
[BrokeredServiceTraceListener]ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener]Added local RPC method "handshake" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.HandshakeAsync(ServiceBrokerClientMetadata, CancellationToken) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener]ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener]Added local RPC method "requestServiceChannel" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker, ServiceActivationOptions, CancellationToken) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener]ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener]Added local RPC method "cancelServiceRequest" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.CancelServiceRequestAsync(Guid) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener]ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener]Added local RPC method "dispose" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.Dispose() (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener]ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener]Added local RPC method "handshake" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.HandshakeAsync(ServiceBrokerClientMetadata, CancellationToken) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener]ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener]Added local RPC method "requestServiceChannel" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker, ServiceActivationOptions, CancellationToken) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener]ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener]Added local RPC method "cancelServiceRequest" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.CancelServiceRequestAsync(Guid) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener]ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener]Listening for events from Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.AvailabilityChanged to raise notification.
[BrokeredServiceTraceListener]ServiceBroker Information: 3 : 
[BrokeredServiceTraceListener]Listening started.
[BrokeredServiceTraceListener]ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener]{"id":2,"method":"handshake"}
[BrokeredServiceTraceListener]ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener]Received: {
  "jsonrpc": "2.0",
  "id": 2,
  "method": "handshake",
  "params": [
    {
      "supportedConnections": "IpcPipe",
      "localServiceHost": {
        "operatingSystem": 0,
        "processArchitecture": 1,
        "runtime": 2,
        "runtimeVersion": "7.0.8"
      }
    }
  ]
}
[BrokeredServiceTraceListener]ServiceBroker Information: 6 : 
[BrokeredServiceTraceListener]Received request "2" for method "handshake".
[LanguageServerHost][08:09:08.237][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 1 documents
[BrokeredServiceTraceListener]ServiceBroker Information: 9 : 
[BrokeredServiceTraceListener]Invoking Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.HandshakeAsync(ServiceBrokerClientMetadata, CancellationToken)
[BrokeredServiceTraceListener]ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener]handshake
[BrokeredServiceTraceListener]ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener]handshake
[BrokeredServiceTraceListener]ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener]{"id":2}
[BrokeredServiceTraceListener]ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener]Sent: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": null
}
[BrokeredServiceTraceListener]ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener]Added local RPC method "availabilityChanged" -> _proxy_Microsoft.ServiceHub.Framework.IRemoteServiceBroker_bdc3252c-0884-4e3c-b8f2-b39db72fd96e.OnAvailabilityChanged(BrokeredServicesChangedEventArgs) (_proxy_Microsoft.ServiceHub.Framework.IRemoteServiceBroker_bdc3252c-0884-4e3c-b8f2-b39db72fd96e)
[BrokeredServiceTraceListener]ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener]IRemoteServiceBroker proffered from remote source: OtherProcessOnSameMachine.
[BrokeredServiceTraceListener]ServiceBroker Information: 1 : 
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[BrokeredServiceTraceListener]OtherProcessOnSameMachine proffered brokered service(s): Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1), Microsoft.VisualStudio.Debugger.ManagedHotReloadService (0.1), vs-intellicode-base-models (0.1), helloServiceHubDotNetHost (0.1), Microsoft.CodeAnalysis.LanguageClient.SolutionSnapshotProvider (0.1).
[BrokeredServiceTraceListener]ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener]{"id":3,"method":"requestServiceChannel"}
[BrokeredServiceTraceListener]ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener]Received: {
  "jsonrpc": "2.0",
  "id": 3,
  "method": "requestServiceChannel",
  "params": [
    {
      "name": "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest",
      "version": "0.1"
    },
    {
      "clientCulture": "en",
      "clientUICulture": "en"
    }
  ]
}
[BrokeredServiceTraceListener]ServiceBroker Information: 6 : 
[BrokeredServiceTraceListener]Received request "3" for method "requestServiceChannel".
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:08.283][Start]textDocument/foldingRange
[BrokeredServiceTraceListener]ServiceBroker Information: 3 : 
[BrokeredServiceTraceListener]Listening started.
[BrokeredServiceTraceListener]ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener]Request for "helloServiceHubDotNetHost (0.1)" will be fulfilled by OtherProcessOnSameMachine
[BrokeredServiceTraceListener]ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener]Requesting proxy to "helloServiceHubDotNetHost (0.1)"
[BrokeredServiceTraceListener]ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener]Request for "helloServiceHubDotNetHost (0.1)" will be fulfilled by OtherProcessOnSameMachine
[BrokeredServiceTraceListener]ServiceBroker Information: 9 : 
[BrokeredServiceTraceListener]Invoking Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker, ServiceActivationOptions, CancellationToken)
[BrokeredServiceTraceListener]ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener]requestServiceChannel
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:08.312][Start]textDocument/codeLens
[BrokeredServiceTraceListener]ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener]Transfer, relatedActivityId=d5ecfe08-526b-4b1c-ae93-d0c59a935483
[BrokeredServiceTraceListener]ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener]Requesting pipe to "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1)"
[BrokeredServiceTraceListener]ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener]Request for "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1)" will be fulfilled by SameProcess
[BrokeredServiceTraceListener]ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener]{"id":2,"method":"handshake"}
[BrokeredServiceTraceListener]ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener]Sent: {
  "traceparent": "00-90db45690983c0448b98af98c854aa3a-d265046b9a3e554a-01",
  "jsonrpc": "2.0",
  "id": 2,
  "method": "handshake",
  "params": [
    {
      "supportedConnections": "Multiplexing, IpcPipe",
      "localServiceHost": {
        "operatingSystem": 0,
        "processArchitecture": 1,
        "runtime": 2,
        "runtimeVersion": "7.0.8"
      }
    }
  ]
}
[LanguageServerHost][08:09:08.328][Start]textDocument/inlayHint
[BrokeredServiceTraceListener]ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener]Transfer, relatedActivityId=1fe2c8bf-3c13-4006-b9f7-b92627989d55
[BrokeredServiceTraceListener]ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener]Requesting proxy to "Microsoft.ServiceHub.Framework.AuthorizationService"
[BrokeredServiceTraceListener]ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener]Request for "Microsoft.ServiceHub.Framework.AuthorizationService" will be fulfilled by SameProcess
[LanguageServerHost][08:09:08.370][Start]workspace/diagnostic
[BrokeredServiceTraceListener]ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener]Request for proxy to "Microsoft.ServiceHub.Framework.AuthorizationService" is Fulfilled by SameProcess: NoExplanation.
[BrokeredServiceTraceListener]ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener]Requesting proxy to "Microsoft.ServiceHub.Framework.AuthorizationService"
[BrokeredServiceTraceListener]ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener]Transfer, relatedActivityId=d5ecfe08-526b-4b1c-ae93-d0c59a935483
[LanguageServerHost][08:09:08.374][End]textDocument/inlayHint
[LanguageServerHost][08:09:08.374][Start]textDocument/documentSymbol
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[BrokeredServiceTraceListener]ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener]Request for pipe to "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1)" is Fulfilled by SameProcess: NoExplanation.
[BrokeredServiceTraceListener]ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener]Requesting pipe to "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1)"
[BrokeredServiceTraceListener]ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener]Transfer, relatedActivityId=1369abde-61fa-43f2-bb20-e462e5bc34d1
[LanguageServerHost]Processing 0 documents
[LanguageServerHost]Closing workspace/diagnostics request
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][08:09:08.386][End]workspace/diagnostic
[BrokeredServiceTraceListener]ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener]{"id":2}
[BrokeredServiceTraceListener]ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener]Received: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": null
}
[BrokeredServiceTraceListener]ServiceBroker Information: 11 : 
[BrokeredServiceTraceListener]Received result for request "2".
[BrokeredServiceTraceListener]ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener]requestServiceChannel
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:08.397][Start]textDocument/semanticTokens/range
[BrokeredServiceTraceListener]ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener]{"id":3}
[BrokeredServiceTraceListener]ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener]Sent: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "requestId": "f1be7027-9a46-4b7e-8f16-233b3f69435d",
    "pipeName": "8852a413a3ba42d0be0a503b7ab34ffd",
    "isEmpty": false
  }
}
[BrokeredServiceTraceListener]ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener]{"id":3,"method":"requestServiceChannel"}
[BrokeredServiceTraceListener]ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener]Sent: {
  "traceparent": "00-90db45690983c0448b98af98c854aa3a-3023a9b97f362b4b-01",
  "jsonrpc": "2.0",
  "id": 3,
  "method": "requestServiceChannel",
  "params": [
    {
      "name": "helloServiceHubDotNetHost",
      "version": "0.1"
    },
    {
      "clientCredentials": {},
      "clientCulture": "da-DK",
      "clientUICulture": "en-US"
    }
  ]
}
[Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.BrokeredServiceBridgeManifest.BrokeredServiceBridgeManifest]Proffered services: Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService,Microsoft.CodeAnalysis.LanguageServer.IHelloWorld (0.1)
[LanguageServerHost]Found 0 diagnostics for DocumentDiagnosticSource: c:\home\tester\TesterProj\Program.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[BrokeredServiceTraceListener]ServiceBroker Information: 13 : 
[BrokeredServiceTraceListener]Connection closing (RemotePartyTerminated: Reached end of stream.). 
[BrokeredServiceTraceListener]ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener]{"id":3}
[BrokeredServiceTraceListener]ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener]Received: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "requestId": "fcb1356d-2fd2-4527-8b9d-3d067fdb8a4e",
    "multiplexingChannelId": 4,
    "isEmpty": false
  }
}
[BrokeredServiceTraceListener]ServiceBroker Information: 11 : 
[BrokeredServiceTraceListener]Received result for request "3".
[LanguageServerHost][08:09:08.449][End]textDocument/diagnostic
[BrokeredServiceTraceListener]ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener]Request for proxy to "helloServiceHubDotNetHost (0.1)" is Fulfilled by OtherProcessOnSameMachine: NoExplanation.
[BrokeredServiceTraceListener]ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener]Requesting proxy to "helloServiceHubDotNetHost (0.1)"
[Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider]Response from remote: Hello, C#! - with love from ServiceHub running on .NET
[LanguageServerHost][08:09:08.466][End]serviceBroker/connect
[LanguageServerHost][08:09:08.475][End]textDocument/codeLens
[LanguageServerHost][08:09:08.490][End]textDocument/foldingRange
[LanguageServerHost][08:09:08.564][End]textDocument/documentSymbol
[LanguageServerHost][08:09:08.779][End]textDocument/semanticTokens/range
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:10.271][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\home\tester\TesterProj\Program.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][08:09:10.280][End]textDocument/diagnostic
[LanguageServerHost][08:09:10.404][Start]workspace/diagnostic
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:10.537][Start]textDocument/codeLens
[LanguageServerHost][08:09:10.538][End]textDocument/codeLens
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:18.108][Start]textDocument/hover
[LanguageServerHost][08:09:18.133][End]textDocument/hover
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:18.329][Start]textDocument/hover
[LanguageServerHost][08:09:18.331][End]textDocument/hover
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:18.550][Start]textDocument/hover
[LanguageServerHost][08:09:18.550][End]textDocument/hover
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:20.173][Start]textDocument/documentHighlight
[LanguageServerHost][08:09:20.201][End]textDocument/documentHighlight
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:20.433][Start]textDocument/codeAction
[LanguageServerHost][08:09:20.754][End]textDocument/codeAction
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:21.538][Start]textDocument/definition
[LanguageServerHost][08:09:21.578][End]textDocument/definition
[LanguageServerHost]c:\home\tester\TesterProj\Program.cs found in workspace MiscellaneousFiles
[LanguageServerHost][08:09:23.664][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\home\tester\TesterProj\Program.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][08:09:23.665][End]textDocument/diagnostic

</details>

Extension version: 2.0.238
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Windows_NT x64 10.0.20348

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.67GB (15.63GB free)|
|Process Argv|--file-uri vscode-remote://ssh-remote%2BREDACTED/c%3A/REDACTED.code-workspace --crash-reporter-id e1474425-8a00-4ec8-8364-fe51656c778f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: REDACTED|
|OS|Windows_NT x64 10.0.20348|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (6 x 2688)|
|Memory (System)|19.53GB (9.51GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30773604
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000
pythonidxpt:30772539
pythondjangotscf:30772537
pythonnocebcf:30773527

```

</details>

**Comment by dibarbet** [comment]
This seems to be a project system issue - after some amount of reloading / rebuilding, the project system no longer passes metadata references to us.  See https://github.com/dotnet/vscode-csharp/issues/5853#issuecomment-1613587381

I have a repo that shows the issue (can't upload it to github for some reason right now), so ping me and I'll send it.

**Comment by lukedays** [comment]
Hi, I'm facing exactly the same issue. After a fresh install of C# + C# Dev Kit, intellisense/go to definition works. But after a full rebuild of the project, it stops working. Uninstalling C# Dev Kit makes it working again. Let me know what additional info I can provide to help solving the issue.

Extension version: 0.2.99

VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)

OS version: Windows_NT x64 10.0.19044

Modes:

 

<details>

<summary>System Info</summary>

 

|Item|Value|

|---|---|

|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|

|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|

|Load (avg)|undefined|

|Memory (System)|31.74GB (11.73GB free)|

|Process Argv|--crash-reporter-id e7047775-f488-49db-8379-55cbe3ea5c6f|

|Screen Reader|no|

|VM|0%|

</details><details>

<summary>A/B Experiments</summary>

 

```

vsliv368:30146709

vsreu685:30147344

python383cf:30185419

vspor879:30202332

vspor708:30202333

vspor363:30204092

vswsl492:30256859

vslsvsres303:30308271

vserr242cf:30382550

pythontb:30283811

vsjup518:30340749

pythonptprofiler:30281270

vsdfh931:30280409

vshan820:30294714

vstes263cf:30335440

vscoreces:30445986

vscod805cf:30301675

binariesv615:30325510

bridge0708:30335490

bridge0723:30353136

vsaa593cf:30376535

pythonvs932:30410667

py29gd2263:30776702

vscaac:30438847

vsclangdc:30486549

c4g48928:30535728

dsvsc012cf:30540253

pynewext54:30695312

azure-dev_surveyone:30548225

282f8724:30602487

pyind779:30671433

f6dab269:30613381

pythonsymbol12:30671437

2i9eh265:30646982

showlangstatbar:30737416

vsctsb:30748421

pythonms35:30701012

03d35959:30757346

pythonfmttext:30731395

pythoncmvfstrcf:30756944

fixshowwlkth:30771522

pythongtdpath:30769146

i26e3531:30780429

pythonnosmt12:30779714

pythonidxpt:30772539

pythonnoceb:30776495

cmakesidepanelv2:30779593

 

```

 

</details>

**Comment by dibarbet** [comment]
In https://github.com/dotnet/vscode-csharp/issues/5849#issuecomment-1614294170 it was mentioned that deleting the obj and bin directories and then re-opening the solution appeared to workaround the problem.

I confirmed this on my local repro as well - with the folder closed I deleted obj/ and bin/, re-opened the solution and it was back to working.  
And like the others mentioned, to get it into a broken state I just had to trigger a rebuild on the project, then reload the window.

**Comment by SheedGuy** [comment]
I am experiencing the same issue. When I open us VSCode and my current workspace reopens, I can see the semantic coloring working correctly for about half a second, then it disappears and I get this issue in my "Projects" output:

"2023-07-02 16:06:48.768 [info] Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-c:\Users\Owen does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

2023-07-02 16:06:50.756 [info] Project system initialization finished. 0 project(s) are loaded, and 1 failed to load."

@dibarbet you mentioned above that this seems to be a Project System Issue and I am inclined to agree. I tried the "reload window" command and I get the same result, the semantic coloring is there for about half a second, then disappears and I get the error from above. 

I just tried closing everything, deleting the bin and obj directories, then restarting, but have essentially had the same issue. This time I got the error mentioned above before even opening one of the files. When I opened Program.cs I immediately saw the semantic coloring, only for it to disappear again about half a second later. Almost seems like something is blocking it from working properly.

I would love to help out and test things if need be, but I am currently a student and this is my first github issue so I am not entirely familiar with the ins and outs of how to be helpful here. I am more than happy to provide any details or try things that might help find a conclusion, just let me know what needs to be done. In any case, I will be tinkering trying to figure out how to get it to work while keeping a close eye on this thread.

**Comment by mkvlrn** [comment]
Was working fine for 2 days stright and then it just won't work anymore. Deleting bin/obj, cleaning, rebuilding, reloading language server, reloading window, restarting: NOTHING works.

I thought at first it had something to do with working in a project inside a WSL environment, but I cloned it in Windows and it's the same.

**Comment by tmeschter** [comment]
@dibarbet Is the fundamental issue here that the Language Service is reloading? The Project System doesn't handle that right now--it won't notice that the LS has gone away, and it has no ability to resend the complete state the LS needs. There is a design for how to address this, but we haven't focused on implementing that yet on the assumption that LS reloads are both rare and the result of a bug in the LS.

Or is the fundamental issue some other problem that occurs even if the LS only loads once and stays up?

**Comment by dibarbet** [comment]
@tmeschter the language server restarting is a separate issue.  In this case we get no metadata references when you first start up (without a reload).

**Comment by tmeschter** [comment]
@dibarbet Ah, ok. I just realized this was copied from https://github.com/dotnet/vscode-csharp/issues/5853.

**Comment by tmeschter** [comment]
Fixed in version 0.3.2.

**Comment by jesperkristensen** [comment]
I tried installing the 0.3.2 preview but I still see the issue. I have made an updated description in #256.

**Comment by ekaradzha-qb** [comment]
+1 Same

**Comment by vunder** [comment]
I had the same after updating to 
It is working, but unstable
After updating to 0.3.2 preview (even restarting VSCode) there was no highlight. After selecting "solution to open" - it was working. However, restarting VSCode - it may or may not work

**Comment by ekaradzha-qb** [comment]
I also start getting an error: 
`An error occurred while installing .NET: The "file" argument must be of type string. Received an instance of Object`, but this maybe be different plugin.

**Comment by vunder** [comment]
I've discovered that the issue is fixed in general but could appear in an unusual way
I'm using v0.3.18. After starting VSCode, is may happen that the highlight is not working: right after start highlight present, after loading extensions - it disappears. But switching to another tab or reopening file - highlight appears back

![image](https://github.com/microsoft/vscode-dotnettools/assets/8414626/2d0ef16d-2cdc-4bd5-8ca5-2446f9665e47)
![image](https://github.com/microsoft/vscode-dotnettools/assets/8414626/a46d9359-e411-4617-9ad1-92712f2bd5ae)

**Comment by kjq** [comment]
I switched to the preview because this was driving me nuts.  It "seems" the tab approach above helps at least for now but its been two days of it works/it doesnt work so we will see.

**Comment by pinkli** [comment]
disable the C# Dev Kit extension solved my issue.

**Comment by ajwells128** [comment]
For the record I'm still getting this issue (devkit v1.3.10). I have to reload my window multiple times a day, which is frustrating. 

I've also noticed a probably related issue where new files don't get picked up by the language server either: they become miscellaneous files. I created an issue about that here, but it's received no attention: https://github.com/microsoft/vscode-dotnettools/issues/897

**Comment by elgendy** [comment]
For the record I'm still getting this issue, the only way to get rid of it is to unfortunately uninstall C# Dev Kit extension.
