### ISSUE TITLE
[WebToolsE2E] TextDocument error occurs when opening a cshtml file.

### ISSUE THREAD

**Issue by v-reinawang** [microsoft/vscode-dotnettools#2263]
**REGRESSION INFO**: Not repro on C# Dev Kit Extension 1.41.11 [Includes C# 2.87.31]

**INSTALL STEPS**

1. Repro OS: Win11 x64 24h2 ENU
2. Install the latest SDK 8.0.413
3. Install latest VSCode (1.103.1)
4. Install public pre-release C# Extension [2.89.19] and C# Dev Kit Extension [1.50.20]

**REPRO STEPS**
1. Create an empty solution and open up the folder in VS Code:
```
md CommandLineProjects
cd CommandLineProjects
dotnet new sln
```
2. Open the folder using VS Code: `code .`
3. Create web application using MVC:
```
md WebApp
cd WebApp
dotnet new mvc -f net8.0
```
4. Run the application: `dotnet run`
5. Create class library
```
cd ..
md ClassLibrary
cd ClassLibrary
dotnet new classlib -f net8.0
```
6. Open Class1.cs in VS Code, add the following method to the class
```
public string GetHello() {
    return "Hello from class library";
}
```
7. Add reference from web app to class library
```
cd ..\WebApp
dotnet add reference ..\ClassLibrary\ClassLibrary.csproj
```
8. Add WebApp and ClassLibrary to the solution
```
cd ..
dotnet sln add WebApp\WebApp.csproj
dotnet sln add ClassLibrary\ClassLibrary.csproj
```
9. Open WebApp/Views/Home/Privacy.cshtml

**NOTE**: This issue is unstable but the repro frequency is very high.

**ACTUAL**
Some TextDocument errors occurred.
<img width="1657" height="902" alt="Image" src="https://github.com/user-attachments/assets/83da732d-ee9a-41a0-aeb8-67ad0ea247f8" />

```
2025-08-20 10:24:08.299 [info] Locating .NET runtime version 9.0.1
2025-08-20 10:24:09.902 [info] Did not find .NET 9.0.1 on path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
2025-08-20 10:24:10.338 [info] Dotnet path: c:\Users\v-reinawang\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\9.0.8~x64~aspnetcore\dotnet.exe
2025-08-20 10:24:10.338 [info] Activating C# + C# Dev Kit...
2025-08-20 10:24:10.893 [info] [stdout] info: Program[0]
      Server started with process ID 11720

2025-08-20 10:24:12.617 [info] [stdout] {"pipeName":"\\\\.\\pipe\\76f39000"}

2025-08-20 10:24:12.617 [info] received named pipe information from server
2025-08-20 10:24:12.617 [info] client has connected to server
2025-08-20 10:24:12.853 [info] [Program] Language server initialized
2025-08-20 10:24:14.553 [info] [textDocument/_vs_getProjectContexts] [Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Using dotnet executable configured on the PATH
2025-08-20 10:24:19.603 [info] [textDocument/_vs_getProjectContexts] [Microsoft.CodeAnalysis.LanguageServer.FileBasedPrograms.FileBasedProgramsProjectSystem] Failed to obtain virtual project for 'c:\Users\v-reinawang\CommandLineProjects\ClassLibrary\Class1.cs' using dotnet run-api. Falling back to directly creating the virtual project.
2025-08-20 10:24:21.098 [info] [textDocument/_vs_getProjectContexts] [Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] .NET BuildHost started from c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.exe reloading to start from C:\Program Files\dotnet\dotnet.exe to match necessary SDK location.
2025-08-20 10:24:25.267 [warning] [textDocument/_vs_getProjectContexts] [LanguageServerProjectLoader] Project c:\Users\v-reinawang\CommandLineProjects\ClassLibrary\Class1.csproj has unresolved dependencies
2025-08-20 10:24:25.336 [info] [textDocument/_vs_getProjectContexts] [LanguageServerProjectLoader] Successfully completed load of c:\Users\v-reinawang\CommandLineProjects\ClassLibrary\Class1.cs
2025-08-20 10:24:28.777 [info] [serviceBroker/connect] [WorkspaceProjectFactoryService] Project C:\Users\v-reinawang\CommandLineProjects\WebApp\WebApp.csproj loaded by C# Dev Kit
2025-08-20 10:24:28.797 [info] [serviceBroker/connect] [WorkspaceProjectFactoryService] Project C:\Users\v-reinawang\CommandLineProjects\ClassLibrary\ClassLibrary.csproj loaded by C# Dev Kit
2025-08-20 10:24:29.672 [error] [workspace/_roslyn_restore] [Microsoft.CodeAnalysis.LanguageServer.Handler.RestoreHandler] Restore completed with errors. See '.NET NuGet Restore' output window for more details.
2025-08-20 10:24:29.691 [info] [textDocument/_vs_getProjectContexts] [LanguageServerProjectLoader] Completed (re)load of all projects in 00:00:15.3054757
2025-08-20 10:24:29.943 [error] [codeLens/resolve] [LSP] StreamJsonRpc.LocalRpcException: Resolve version '2025-08-20T10:24:25.2908785Z-10023-0' does not match current version '2025-08-20T10:24:29.8908285Z-10046-0'
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.ResolveCodeLensAsync(CodeLens request, Document document, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 61
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
2025-08-20 10:24:29.944 [error] [codeLens/resolve] [LSP] StreamJsonRpc.LocalRpcException: Resolve version '2025-08-20T10:24:25.2908785Z-10023-0' does not match current version '2025-08-20T10:24:29.8908285Z-10046-0'
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.ResolveCodeLensAsync(CodeLens request, Document document, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 61
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
2025-08-20 10:24:42.800 [error] Request textDocument/diagnostic failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-20 10:24:42.800 [error] Document pull failed for text document file:///c%3A/Users/v-reinawang/CommandLineProjects/WebApp/Views/Home/Privacy.cshtml
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-20 10:24:42.803 [error] Request textDocument/inlayHint failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-20 10:24:42.805 [error] Request textDocument/codeAction failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-20 10:24:42.807 [error] Request textDocument/documentSymbol failed.
  Message: Could not get the generated document
  Code: -32000 
[object Object]
2025-08-20 10:24:42.810 [error] Request textDocument/documentSymbol failed.
  Message: Could not get the generated document
  Code: -32000 
[object Object]
2025-08-20 10:24:42.954 [error] Request textDocument/semanticTokens/range failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-20 10:26:19.336 [error] Request textDocument/semanticTokens/range failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-20 10:26:19.481 [error] Request textDocument/inlayHint failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
```

**EXPECTED**
There will be no errors.

**Comment by claudiaregio** [comment]
@davidwengier This appears to be a regression, could you take a look when you get a chance?

**Comment by davidwengier** [comment]
@v-reinawang Can you include the Razor Log output here for reference? I suspect this is the same issue as https://github.com/dotnet/vscode-csharp/issues/8512, which should be fixed by the next Razor insertion

**Comment by v-reinawang** [comment]
Razor Log output:

```
2025-08-21 04:59:44.520 [info] --------------------------------------------------------------------------------
2025-08-21 04:59:44.520 [info] Razor.VSCode version 10.0.0-preview.25411.5
2025-08-21 04:59:44.520 [info] --------------------------------------------------------------------------------
2025-08-21 04:59:44.520 [info] Razor's log level is currently set to 'Info'
2025-08-21 04:59:44.521 [info]  - To change Razor's log level use the gear icon on the output window
2025-08-21 04:59:44.521 [info]  - To report issues invoke the 'Report a Razor issue' command via the command palette.
2025-08-21 04:59:44.521 [info] -----------------------------------------------------------------------------------------------------------------------------
2025-08-21 04:59:44.521 [info] 
2025-08-21 04:59:50.185 [info] [Razor.LanguageClient.Cohost.RazorCohostDynamicRegistrationService] Requesting 23 Razor cohost registrations.
2025-08-21 04:59:50.238 [info] [Razor.LanguageClient.Cohost.CohostStartupService] Razor extension startup finished.
2025-08-21 05:00:12.363 [error] [Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer] Error getting Html text for C:\Users\v-reinawang\CommandLineProjects\WebApp\Views\Home\Privacy.cshtml. Html document contents will be staleSystem.InvalidOperationException: Could not get the code document   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Remote.Razor.RemoteHtmlDocumentService.GetHtmlDocumentTextAsync(RemoteDocumentContext documentContext, CancellationToken cancellationToken)   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer.PublishHtmlDocumentAsync(TextDocument document, RazorDocumentVersion requestedVersion, CancellationToken cancellationToken)
[Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer] Error getting Html text for C:\Users\v-reinawang\CommandLineProjects\WebApp\Views\Home\Privacy.cshtml. Html document contents will be staleSystem.InvalidOperationException: Could not get the code document   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Remote.Razor.RemoteHtmlDocumentService.GetHtmlDocumentTextAsync(RemoteDocumentContext documentContext, CancellationToken cancellationToken)   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer.PublishHtmlDocumentAsync(TextDocument document, RazorDocumentVersion requestedVersion, CancellationToken cancellationToken)
Stack Trace:
Error: [Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer] Error getting Html text for C:\Users\v-reinawang\CommandLineProjects\WebApp\Views\Home\Privacy.cshtml. Html document contents will be staleSystem.InvalidOperationException: Could not get the code document   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Remote.Razor.RemoteHtmlDocumentService.GetHtmlDocumentTextAsync(RemoteDocumentContext documentContext, CancellationToken cancellationToken)   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer.PublishHtmlDocumentAsync(TextDocument document, RazorDocumentVersion requestedVersion, CancellationToken cancellationToken)
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:12.373 [error] [textDocument/codeAction] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteCodeActionsService.GetCodeActionRequestInfoAsync(RemoteDocumentContext context, VSCodeActionParams request, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostCodeActionsEndpoint.HandleRequestAsync(VSCodeActionParams request, TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
[textDocument/codeAction] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteCodeActionsService.GetCodeActionRequestInfoAsync(RemoteDocumentContext context, VSCodeActionParams request, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostCodeActionsEndpoint.HandleRequestAsync(VSCodeActionParams request, TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
Stack Trace:
Error: [textDocument/codeAction] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteCodeActionsService.GetCodeActionRequestInfoAsync(RemoteDocumentContext context, VSCodeActionParams request, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostCodeActionsEndpoint.HandleRequestAsync(VSCodeActionParams request, TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:12.407 [error] [textDocument/inlayHint] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteInlayHintService.GetInlayHintsAsync(RemoteDocumentContext context, InlayHintParams inlayHintParams, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostInlayHintEndpoint.HandleRequestAsync(InlayHintParams request, TextDocument razorDocument, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
[textDocument/inlayHint] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteInlayHintService.GetInlayHintsAsync(RemoteDocumentContext context, InlayHintParams inlayHintParams, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostInlayHintEndpoint.HandleRequestAsync(InlayHintParams request, TextDocument razorDocument, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
Stack Trace:
Error: [textDocument/inlayHint] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteInlayHintService.GetInlayHintsAsync(RemoteDocumentContext context, InlayHintParams inlayHintParams, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostInlayHintEndpoint.HandleRequestAsync(InlayHintParams request, TextDocument razorDocument, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:12.426 [error] [textDocument/diagnostic] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDiagnosticsService.GetDiagnosticsAsync(RemoteDocumentContext context, Diagnostic[] csharpDiagnostics, Diagnostic[] htmlDiagnostics, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentPullDiagnosticsEndpointBase`2.GetDiagnosticsAsync(TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.DocumentPullDiagnosticsEndpoint.HandleRequestAsync(DocumentDiagnosticParams request, TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
[textDocument/diagnostic] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDiagnosticsService.GetDiagnosticsAsync(RemoteDocumentContext context, Diagnostic[] csharpDiagnostics, Diagnostic[] htmlDiagnostics, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentPullDiagnosticsEndpointBase`2.GetDiagnosticsAsync(TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.DocumentPullDiagnosticsEndpoint.HandleRequestAsync(DocumentDiagnosticParams request, TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
Stack Trace:
Error: [textDocument/diagnostic] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDiagnosticsService.GetDiagnosticsAsync(RemoteDocumentContext context, Diagnostic[] csharpDiagnostics, Diagnostic[] htmlDiagnostics, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentPullDiagnosticsEndpointBase`2.GetDiagnosticsAsync(TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.DocumentPullDiagnosticsEndpoint.HandleRequestAsync(DocumentDiagnosticParams request, TextDocument razorDocument, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:12.427 [error] [textDocument/documentSymbol] [LSP] System.InvalidOperationException: Could not get the generated document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDocumentSymbolService.GetDocumentSymbolsAsync(RemoteDocumentContext context, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentSymbolEndpoint.HandleRequestAsync(TextDocument razorDocument, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
[textDocument/documentSymbol] [LSP] System.InvalidOperationException: Could not get the generated document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDocumentSymbolService.GetDocumentSymbolsAsync(RemoteDocumentContext context, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentSymbolEndpoint.HandleRequestAsync(TextDocument razorDocument, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
Stack Trace:
Error: [textDocument/documentSymbol] [LSP] System.InvalidOperationException: Could not get the generated document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDocumentSymbolService.GetDocumentSymbolsAsync(RemoteDocumentContext context, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentSymbolEndpoint.HandleRequestAsync(TextDocument razorDocument, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:12.435 [error] [textDocument/documentSymbol] [LSP] System.InvalidOperationException: Could not get the generated document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDocumentSymbolService.GetDocumentSymbolsAsync(RemoteDocumentContext context, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentSymbolEndpoint.HandleRequestAsync(TextDocument razorDocument, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
[textDocument/documentSymbol] [LSP] System.InvalidOperationException: Could not get the generated document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDocumentSymbolService.GetDocumentSymbolsAsync(RemoteDocumentContext context, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentSymbolEndpoint.HandleRequestAsync(TextDocument razorDocument, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
Stack Trace:
Error: [textDocument/documentSymbol] [LSP] System.InvalidOperationException: Could not get the generated document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteDocumentSymbolService.GetDocumentSymbolsAsync(RemoteDocumentContext context, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostDocumentSymbolEndpoint.HandleRequestAsync(TextDocument razorDocument, Boolean useHierarchicalSymbols, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:12.473 [error] [Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer] Error getting Html text for C:\Users\v-reinawang\CommandLineProjects\WebApp\Views\Home\Privacy.cshtml. Html document contents will be staleSystem.InvalidOperationException: Could not get the code document   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Remote.Razor.RemoteHtmlDocumentService.GetHtmlDocumentTextAsync(RemoteDocumentContext documentContext, CancellationToken cancellationToken)   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer.PublishHtmlDocumentAsync(TextDocument document, RazorDocumentVersion requestedVersion, CancellationToken cancellationToken)
[Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer] Error getting Html text for C:\Users\v-reinawang\CommandLineProjects\WebApp\Views\Home\Privacy.cshtml. Html document contents will be staleSystem.InvalidOperationException: Could not get the code document   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Remote.Razor.RemoteHtmlDocumentService.GetHtmlDocumentTextAsync(RemoteDocumentContext documentContext, CancellationToken cancellationToken)   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer.PublishHtmlDocumentAsync(TextDocument document, RazorDocumentVersion requestedVersion, CancellationToken cancellationToken)
Stack Trace:
Error: [Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer] Error getting Html text for C:\Users\v-reinawang\CommandLineProjects\WebApp\Views\Home\Privacy.cshtml. Html document contents will be staleSystem.InvalidOperationException: Could not get the code document   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Remote.Razor.RemoteHtmlDocumentService.GetHtmlDocumentTextAsync(RemoteDocumentContext documentContext, CancellationToken cancellationToken)   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.HtmlDocumentSynchronizer.PublishHtmlDocumentAsync(TextDocument document, RazorDocumentVersion requestedVersion, CancellationToken cancellationToken)
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:12.482 [error] [textDocument/semanticTokens/range] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Guid correlationId, Boolean colorBackground, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteSemanticTokensService.GetSemanticTokensDataAsync(RemoteDocumentContext context, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostSemanticTokensRangeEndpoint.HandleRequestAsync(TextDocument razorDocument, LinePositionSpan span, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
[textDocument/semanticTokens/range] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Guid correlationId, Boolean colorBackground, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteSemanticTokensService.GetSemanticTokensDataAsync(RemoteDocumentContext context, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostSemanticTokensRangeEndpoint.HandleRequestAsync(TextDocument razorDocument, LinePositionSpan span, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
Stack Trace:
Error: [textDocument/semanticTokens/range] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Guid correlationId, Boolean colorBackground, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteSemanticTokensService.GetSemanticTokensDataAsync(RemoteDocumentContext context, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostSemanticTokensRangeEndpoint.HandleRequestAsync(TextDocument razorDocument, LinePositionSpan span, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:15.254 [error] [textDocument/semanticTokens/range] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Guid correlationId, Boolean colorBackground, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteSemanticTokensService.GetSemanticTokensDataAsync(RemoteDocumentContext context, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostSemanticTokensRangeEndpoint.HandleRequestAsync(TextDocument razorDocument, LinePositionSpan span, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
[textDocument/semanticTokens/range] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Guid correlationId, Boolean colorBackground, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteSemanticTokensService.GetSemanticTokensDataAsync(RemoteDocumentContext context, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostSemanticTokensRangeEndpoint.HandleRequestAsync(TextDocument razorDocument, LinePositionSpan span, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
Stack Trace:
Error: [textDocument/semanticTokens/range] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Guid correlationId, Boolean colorBackground, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.SemanticTokens.AbstractRazorSemanticTokensInfoService.GetSemanticTokensAsync(DocumentContext documentContext, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteSemanticTokensService.GetSemanticTokensDataAsync(RemoteDocumentContext context, LinePositionSpan span, Boolean colorBackground, Guid correlationId, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostSemanticTokensRangeEndpoint.HandleRequestAsync(TextDocument razorDocument, LinePositionSpan span, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
2025-08-21 05:00:15.502 [error] [textDocument/inlayHint] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteInlayHintService.GetInlayHintsAsync(RemoteDocumentContext context, InlayHintParams inlayHintParams, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostInlayHintEndpoint.HandleRequestAsync(InlayHintParams request, TextDocument razorDocument, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
[textDocument/inlayHint] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteInlayHintService.GetInlayHintsAsync(RemoteDocumentContext context, InlayHintParams inlayHintParams, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostInlayHintEndpoint.HandleRequestAsync(InlayHintParams request, TextDocument razorDocument, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
Stack Trace:
Error: [textDocument/inlayHint] [LSP] System.InvalidOperationException: Could not get the code document
   at Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem.RemoteDocumentSnapshot.GetGeneratedOutputAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentContext.<GetCodeDocumentAsync>g__GetCodeDocumentCoreAsync|19_0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Remote.Razor.RemoteInlayHintService.GetInlayHintsAsync(RemoteDocumentContext context, InlayHintParams inlayHintParams, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.VisualStudioCode.RazorExtension.Services.VSCodeRemoteServiceInvoker.TryInvokeAsync[TService,TResult](Solution solution, Func`4 invocation, CancellationToken cancellationToken, String callerFilePath, String callerMemberName)
   at Microsoft.VisualStudio.Razor.LanguageClient.Cohost.CohostInlayHintEndpoint.HandleRequestAsync(InlayHintParams request, TextDocument razorDocument, Boolean displayAllOverride, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken)
    at RO.log (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1205:18867)
    at c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:1210:33608
    at mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:51:1620)
    at Mr (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7629)
    at Immediate._onImmediate (c:\Users\v-reinawang\.vscode\extensions\ms-dotnettools.csharp-2.89.19-win32-x64\dist\extension.js:50:7324)
    at processImmediate (node:internal/timers:485:21)
```

**Comment by yinjiehe01** [comment]
This problem also occurs when renaming `<Counter></Counter>` component in Home page and then open the newly named file.
![Image](https://github.com/user-attachments/assets/e40b2d3a-2719-4cd9-a55a-901c9d800b86)
Razor logs:
```
2025-08-26 05:34:19.231 [info] Locating .NET runtime version 9.0.1
2025-08-26 05:34:19.491 [info] Did not find .NET 9.0.1 on path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
2025-08-26 05:34:19.670 [info] Dotnet path: /home/nicole/.config/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/9.0.8~x64~aspnetcore/dotnet
2025-08-26 05:34:19.670 [info] Activating C# + C# Dev Kit...
2025-08-26 05:34:19.898 [info] [stdout] info: Program[0]
      Server started with process ID 2485

2025-08-26 05:34:20.574 [info] [stdout] {"pipeName":"/tmp/37f2271e.sock"}

2025-08-26 05:34:20.574 [info] received named pipe information from server
2025-08-26 05:34:20.574 [info] client has connected to server
2025-08-26 05:34:20.733 [info] [Program] Language server initialized
2025-08-26 05:34:33.531 [info] Locating .NET runtime version 9.0.1
2025-08-26 05:34:33.824 [info] Did not find .NET 9.0.1 on path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
2025-08-26 05:34:33.964 [info] Dotnet path: /home/nicole/.config/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/9.0.8~x64~aspnetcore/dotnet
2025-08-26 05:34:33.964 [info] Activating C# + C# Dev Kit...
2025-08-26 05:34:34.090 [info] [stdout] info: Program[0]
      Server started with process ID 2859

2025-08-26 05:34:34.586 [info] [stdout] {"pipeName":"/tmp/7fd987b9.sock"}

2025-08-26 05:34:34.586 [info] received named pipe information from server
2025-08-26 05:34:34.586 [info] client has connected to server
2025-08-26 05:34:34.728 [info] [Program] Language server initialized
2025-08-26 05:34:39.895 [info] [serviceBroker/connect] [WorkspaceProjectFactoryService] Project /home/nicole/BlazorApp2/BlazorApp2/BlazorApp2.csproj loaded by C# Dev Kit
2025-08-26 05:35:17.078 [error] Request textDocument/codeAction failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:17.079 [error] Request textDocument/diagnostic failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:17.079 [error] Document pull failed for text document file:///home/nicole/BlazorApp2/BlazorApp2/Components/Pages/Counterer.razor
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:17.080 [error] Request textDocument/documentSymbol failed.
  Message: Couldn't get the source generated document for a hint name that we got from the generator?
  Code: -32000 
[object Object]
2025-08-26 05:35:17.107 [error] Request textDocument/inlayHint failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:17.362 [error] Request textDocument/documentSymbol failed.
  Message: Couldn't get the source generated document for a hint name that we got from the generator?
  Code: -32000 
[object Object]
2025-08-26 05:35:17.594 [error] Request textDocument/semanticTokens/range failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:21.857 [error] Request textDocument/hover failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:42.481 [error] Request textDocument/hover failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:44.620 [error] Request textDocument/inlayHint failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:44.665 [error] Request textDocument/semanticTokens/range failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
2025-08-26 05:35:48.797 [error] Request textDocument/codeAction failed.
  Message: Could not get the code document
  Code: -32000 
[object Object]
```

**Comment by claudiaregio** [comment]
@yinjiehe01 I am no longer able to repro this issue with C#DK V1.50.33 / C# V2.90.51 combo, especially when renaming the symbol and opening the updated file. Validating as fixed unless you say you're still reproing it.

**Comment by yinjiehe01** [comment]
@claudiaregio This issue was repro on C#DK 1.50.20/C# 2.89.19, I am sorry not to add this information. I will check it with C#DK V1.50.33 / C# V2.90.51

**Comment by v-reinawang** [comment]
Verify that this issue has been fixed in C#DK V1.50.33 / C# V2.90.51

**Comment by Itschotsch** [comment]
@v-reinawang I am using C#DK V1.50.33 and C# V2.90.51 in VS Code 1.104.0-insider and the issue still occurs.

**Comment by davidwengier** [comment]
@Itschotsch Can you please use the Report Razor Issue command so we can capture logs etc. or provide more information about what exactly the scenario is that you're doing, and what you're seeing?

**Comment by claudiaregio** [comment]
@Itschotsch Are your repro steps identical to the OP's? I walked through the exact same steps as the OP and was not encountering this issue.

**Comment by Itschotsch** [comment]
I just updated to C# DK 1.50.51, C# 2.91.30 and VS Code 1.105.0-insider and the issue has gone away.
I had enabled `Dotnet › Server: Suppress Lsp Error Toasts` in the settings but after disabling this option and restarting, everything seems to work.
