### ISSUE TITLE
[WebToolsE2E][Green]"Show all template options" doesn't work

### ISSUE THREAD

**Issue by Susie-1989** [microsoft/vscode-dotnettools#2488]
**REGRESSION INFO**: Not repro on Oct 2025 release C#DK 1.80.2[include C# 2.100.5]

**INSTALL STEPS**

1. Win11 x64 24h2 ENU
2. Install Visual Studio Code 1.106.0
3. Install the SDK 10.0.100
4. Install November 2025 Pre-release #1 C# DK 1.81.7 [includes C# 2.101.21]

**REPRO STEPS**

1. Open vs code select "Create .NET Project".
2.  Select "ASP.NET Core Web App(Razor Pages)" > select a folder > Press "Enter" > select "Show all template options"

**ACTUAL**  "Show all template options" doesn't work

https://github.com/user-attachments/assets/5be7edf7-1d86-4e26-8380-6f5fbfa8feda

**EXPECTED** "Show all template options" works as below screenshot.

<img width="970" height="341" alt="Image" src="https://github.com/user-attachments/assets/8541b2a7-1936-4a60-85fa-67833b99f2b2" />

**Comment by yinjiehe01** [comment]
Not repro on Linux OS.

![Image](https://github.com/user-attachments/assets/5ac7a6dd-250e-44df-be31-fa769b28376a)

**Comment by drewnoakes** [comment]
Also noticed that "Discovering project templates..." lingers in the status bar.

<img width="497" height="99" alt="Image" src="https://github.com/user-attachments/assets/9545ba75-3bee-4639-8cc9-fe76a36a82f4" />

**Comment by vsccarl** [comment]
@drewnoakes are there any updates on a fix for this? The validation team is concerned this should be blocking for Nov release.

**Comment by drewnoakes** [comment]
Fixed in two PRs, currently in review.

**Comment by Susie-1989** [comment]
@claudiaregio This issue still repro in C# Dev Kit Jan Prerelease 1.91.6(C#2.111.2 ), could you help take a look?

For C# Dev Kit release version 1.90.2(C#2.110.4), it only has two items "Framework" and "Authentication type"

<img width="1070" height="178" alt="Image" src="https://github.com/user-attachments/assets/c1308225-8706-449f-bdef-6b5b4998f7a1" />

**Comment by drewnoakes** [comment]
I think we need to replace the use of Newtonsoft.Json for loading host data. It's not working well with our Native AOT build. I've started migrating to System.Text.Json which was built for this scenario.

**Comment by Theakayuki** [comment]
Any updates on this, been on version 1.80.7 so I can create projects for dotnet on VS code C# dev kit properly?

**Comment by Susie-1989** [comment]
This issue works well  in Jan prerelease 2 C# DK1.92.5(include C#2.112.45)

**Comment by drewnoakes** [comment]
This may have been fixed at the same time as #2873

**Comment by Susie-1989** [comment]
This issue works well in April prerelease 1 C# DK3.11.200(include C#2.133.5)
