### ISSUE TITLE
[WebToolsE2E][Green]Making change in .razor file in Blazor Web App ~ 10.0 ~ WebAssembly ~ Per page/component , press hot reload button, warning "[warning]  BlazorApp1 (net10.0): No changes applied to client because they are not supported..." show up

### ISSUE THREAD

**Issue by Susie-1989** [microsoft/vscode-dotnettools#2539]
REGRESSION INFO: Not a Regression

**INSTALL STEPS**

1. Win11 x64 23h2 ENU
2. Install the SDK 10.0.100
3. Install VS Code Stable - 1.106.1
4. Install Oct 2025 release C#DK 1.80.7[include C# 2.100.11]

**REPRO STEPS**

1. Go to Settings > Search 'Hot Reload' > Enables C# Hot Reload while debugging
2. Open vs code > Create .NET Project > Blazor Web App ~ 10.0 ~ WebAssembly ~ Per page/component 
3. Right click the project > Debug > Start New Instance 
4. Open Home.razor file and change "`<h1>Hello, world!</h1>`" to "`<h1>Hello, world11!</h1>`"
5. Press "Hot Reload" button

Note: 
1.This issue also repro  Blazor Web App ~ 10.0 ~ Auto(Server and WebAssembly) ~ Per page/component /Global
2. Even if there is an warning message, the page can be updated with the new change automatically.

**ACTUAL**  Warning "[warning]  BlazorApp1 (net10.0): No changes applied to client because they are not supported by the runtime." show up

<img width="1410" height="719" alt="Image" src="https://github.com/user-attachments/assets/27ccbdc7-aa7f-466e-bd00-ede376bd5540" />

**EXPECTED**  No warning shows.

**Comment by dbreshears** [comment]
@tmat .  Can you look at this warning

**Comment by tmat** [comment]
@LittleLittleCloud 
It's likely this is caused by the project system not passing Hot Reload capabilities to the debugger.

The project system needs to read `WebAssemblyHotReloadCapabilities` msbuild property and pass the result to the debugger (with fallback for projects targeting TFM <10.0: https://github.com/dotnet/sdk/blob/main/src/BuiltInTools/HotReloadClient/Web/WebAssemblyHotReloadClient.cs#L42-L65

**Comment by LittleLittleCloud** [comment]
Just talked to @tmat  offline,, the project system sets `WebAssemblyHotReloadCapabilities` in a proper way...

Also I'm not able to reproduce this issue on my end,,, @Susie-1989 do you see this bug constantly?

**Comment by Susie-1989** [comment]
@LittleLittleCloud I am able to reproduce this issue, below is video

https://github.com/user-attachments/assets/08d28759-5c2a-4ec8-8ef8-8f8a2dcb3edd

**Comment by LittleLittleCloud** [comment]
#2538

**Comment by JakeRadMSFT** [comment]
Solved by other bug?

**Comment by Susie-1989** [comment]
> Solved by other bug?

No, this issue still reproduces in Jan prelease 3.2 C# devkit 1.93.20(C#2.114.6)

**Comment by Susie-1989** [comment]
This issue still reproduces in Feb prerelease 1 C# DK2.11.4(include C#2.121.32)

**Comment by v-reinawang** [comment]
This issue also repro on .NET 11.0.

<img width="809" height="85" alt="Image" src="https://github.com/user-attachments/assets/893c10f9-63eb-47b4-bb30-2059ccb2f080" />
