### ISSUE TITLE
[BUG] Unity Visual Studio package deregisters my TSK VSCode Editor package

### ISSUE THREAD

**Issue by Chizaruu** [microsoft/vscode-dotnettools#323]
### Describe the Issue

The Visual Studio package [deregisters ](https://github.com/Chizaruu/com.tsk.ide.vscode/issues/77)my package from being an option in External tools due to `LegacyVisualStudioCodePackageDisabler` in `VisualStudioEditor.cs` within its package.

```
#if UNITY_2019_4_OR_NEWER && !UNITY_2020
		[InitializeOnLoadMethod]
		static void LegacyVisualStudioCodePackageDisabler()
		{
			// disable legacy Visual Studio Code packages
			var editor = CodeEditor.Editor.GetCodeEditorForPath("code.cmd");
			if (editor == null)
				return;

			if (editor is VisualStudioEditor)
				return;

			CodeEditor.Unregister(editor);
		}
#endif
```

### Steps To Reproduce

1. Install the Visual Studio Editor package
2. Install the [TSK VSCode Editor](https://github.com/Chizaruu/com.tsk.ide.vscode) package
3. See only Visual Studio Editor as an options

### Expected Behavior

Both packages can be used at the same time.

### Environment Information

Unity 2021.3+

Rest is not required.

**Comment by sailro** [comment]
Hi @Chizaruu, we updated our package to only disable the legacy `com.unity.ide.vscore` package. 

Regarding _"Both packages can be used at the same time"_, yes you are right for the discovery and when you explicitly select an installation during the session.

But I fear that only the fullpath to the selected external editor is stored between executions, so when restarting Unity, the Unity Editor will query all CodeEditors and the first to respond "I'm able to handle this" will manage. Depending on the type load order we have no clue of which one will be activated first.

cc @miniwolf

What do you think?

**Comment by Chizaruu** [comment]
Thanks for the update! 🎉

Bummer about the load order issue. 😅

**Comment by jbevain** [comment]
The `Visual Studio Editor Package` version `2.0.21` is now available and will only unregister the `Visual Studio Code Editor Package`. As discussed here, it doesn't solve the limitation of the Unity API. Thanks for reporting this!
