### ISSUE TITLE
[BUG] Language Server Fails to start.

### ISSUE THREAD

**Issue by slowsigma** [microsoft/vscode-dotnettools#391]
### Describe the Issue

Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:58:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:01 AM] Connection to server got closed. Server will restart.
true
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:58:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:01 AM] Connection to server got closed. Server will restart.
true
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:58:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:01 AM] Connection to server got closed. Server will restart.
true
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:01 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 10:58:01 AM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 10:58:01 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at s.shutdown (c:\Users\my.account\.vscode\extensions\ms-dotnettools.csharp-2.0.357-win32-ia32\dist\extension.js:2:2241411)
	at s.stop (c:\Users\my.account\.vscode\extensions\ms-dotnettools.csharp-2.0.357-win32-ia32\dist\extension.js:2:2240992)
	at s.stop (c:\Users\my.account\.vscode\extensions\ms-dotnettools.csharp-2.0.357-win32-ia32\dist\extension.js:2:2404164)
	at s.handleConnectionError (c:\Users\my.account\.vscode\extensions\ms-dotnettools.csharp-2.0.357-win32-ia32\dist\extension.js:2:2247499)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 10:58:01 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 10:58:01 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 10:58:01 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 10:58:01 AM] Connection to server got closed. Server will restart.
true
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:58:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:01 AM] The Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by slowsigma** [comment]
Windows 10,
Associated Visual Studio Subscription
Highest Runtime: 7.0.10
Highest SDK: 7.0.400
VSCode: 1.81.1

**Comment by nagilson** [comment]
This is the same as https://github.com/dotnet/vscode-csharp/issues/5877

For now you need to delete the folder found in (command 'open extensions folder'). VS Code has installed the C# extension or CDK on the incorrect architecture, it installs a fallback architecture during release ix the x64 architecture is not available per @dibarbet. The hostfxr cannot load if the architecture is incorrect.

No fix in place from VS Code at this time to give us control over this issue, maybe CDK/C# should catch 0x800700C1 and return a more refined error @arkalyanms

**Comment by Shimii** [comment]
Had a similar issue. Unfortunately deleting the folder and reinstalling the extensions did not help. It kept installing the ia32 version whereas I needed the x64 version. I had to delete the folder and manually download the correct version for the correct architecture from the marketplace and install it manually. This solved the issue for me.

**Comment by nagilson** [comment]
We will try using a different method to detect the architecture to install and hope that will fix this issue. Tracking that work here https://github.com/dotnet/vscode-dotnet-runtime/issues/1338

**Comment by nagilson** [comment]
this is fixed in 1.8.0

**Comment by sigmaxf** [comment]
Still happening: 
Windows 11
VSCode 1.84.2
C# Extension: v2.10.28

Tried everything described previously, still no success.

**Comment by sigmaxf** [comment]
Solved it by independently downloading and installing .net 8.0

**Comment by justinmchase** [comment]
> For now you need to delete the folder...

Which folder?

**Comment by yolandacorreia** [comment]
> > For now you need to delete the folder...
> 
> Which folder?

ms-dotnettools.csharp and its dependencies (e.g. csdevkit, vscodeintellicode-csharp)

**Comment by drumscanner** [comment]
I have the same or similar issue:
VS Code:

Version: 1.87.1
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:07.287Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-25-generic snap

 Fresh VS Code installation, only C# Dev Kit installed:

> ~/.vscode/extensions$ ls -l
total 20
-rw-rw-r--  1 sergei sergei 2545 Mar 10 18:48 extensions.json
drwxrwxr-x  9 sergei sergei 4096 Mar 10 18:48 ms-dotnettools.csdevkit-1.3.10-linux-x64
drwxrwxr-x 16 sergei sergei 4096 Mar 10 18:48 ms-dotnettools.csharp-2.18.16-linux-x64
drwxrwxr-x  4 sergei sergei 4096 Mar 10 18:47 ms-dotnettools.vscode-dotnet-runtime-2.0.2
drwxrwxr-x  7 sergei sergei 4096 Mar 10 18:48 ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64

Log file shows

Using dotnet configured on PATH
Dotnet path: /snap/dotnet-sdk/236/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stderr] Failed to load /snap/dotnet-sdk/236/shared/Microsoft.NETCore.App/8.0.2/libcoreclr.so, error: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/core20/current/lib/x86_64-linux-gnu/librt.so.1)
[Error - 6:59:32 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Timeout. Named pipe information not received from server.
	at q.<anonymous> (/home/sergei/.vscode/extensions/ms-dotnettools.csharp-2.18.16-linux-x64/dist/extension.js:2:1291159)
	at Generator.next (<anonymous>)
	at s (/home/sergei/.vscode/extensions/ms-dotnettools.csharp-2.18.16-linux-x64/dist/extension.js:2:1281031)

VS Code freezes when dotnet project folder is opened

**Comment by kdcllc** [comment]
I am having the issues with C# DevKit starting

```
Version: 1.89.0-insider
Commit: ed6c6d3f28fa4cb66f6d73918365e41fb81db14c
Date: 2024-04-08T05:50:20.905Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-27-generic snap
```

With the following error:

```
sing dotnet configured on PATH
Dotnet path: /home/kdcll/.dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 2:20:16 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.h._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
    at Function.i._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
    at Function.t._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35317)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at h (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/binding.js:9:1)
    at Module.o._compile (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.h._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
    at Function.i._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
    at Function.t._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35317)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at h (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/backend.js:18:19)
    at Module.o._compile (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.h._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
    at Function.i._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
    at Function.t._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35317)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at h (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/index.js:21:17)
    at Module.o._compile (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.h._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
    at Function.i._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
    at Function.t._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35317)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at h (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:4:647)
    at Object.884 (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1301229)
    at __webpack_require__ (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
    at Object.7974 (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290437)
    at __webpack_require__ (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
    at Object.5175 (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290103)
    at __webpack_require__ (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
    at Object.3843 (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:323341)
    at __webpack_require__ (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
    at Object.4054 (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:335524)
    at __webpack_require__ (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
    at Object.8746 (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:312316)
    at __webpack_require__ (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
    at Object.9972 (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1194711)
    at __webpack_require__ (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
    at Object.8902 (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1196784)
    at __webpack_require__ (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
    at /home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1450511
    at /home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451450
    at Object.<anonymous> (/home/kdcll/.vscode-insiders/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451489)
    at Module.o._compile (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.h._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
    at Function.i._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
    at Function.t._load (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35317)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Function.i [as __$__nodeRequire] (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/loader.js:5:98)
    at m.xb (/snap/code-insiders/1599/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:30898)
    at async Promise.all (index 0
```

**Comment by kdcllc** [comment]
resolved by the following:

```bash

snap remove code-insiders

# download the latest https://code.visualstudio.com/insiders/# and installing it
sudo dpkg -i code-insiders_1.89.0-1712556981_amd64.deb
```

**Comment by MarsFresco** [comment]
> I am having the issues with C# DevKit starting
> 
> With the following error:
> 
> ```
> sing dotnet configured on PATH
> Dotnet path: /home/kdcll/.dotnet/dotnet
> Activating C# + C# Dev Kit + C# IntelliCode...
> [Error - 2:20:16 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
> Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
> ```

Had same problem, updated to v1.5.12 (pre-release). It is OK now.

**Comment by gcalabro-rli** [comment]
Is this ever going to get fixed?

**Comment by mohitNarang** [comment]
I had been getting this error message (mac os x, m2 pro apple silicon) since updating the vscode extensions. 

The problem was in the link to "Dotnet path" variable in the settings for the extension. 

The path set by the extension was: "/usr/local/share/dotnet/dotnet". **This was wrong in my case because it somehow added another folder called 'dotnet' below the actual /user/local/share/dotnet.** 

To fix it, i changed the path to where your dotnet is installed. In my case it was : /usr/local/share/dotnet

**Comment by justinmchase** [comment]
I've seen the "successfully connected..." message appear right after the failure happens. In my opinion its "working" fine but the timeout is 30s which is just way too low.

Is there a way to increase the timeout its using to wait for the server? I would set it to 5m to be honest.

**Comment by prosa21** [comment]
@mohitNarang how did you do that? I don't see any configurable path on the extension's settings.
When the extension is initializing it writes:
```
Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
```

The path to dotnet in PATH is correct `/usr/local/share/dotnet`, the thing is that the executable inside that folder is also called dotnet, hence the double dotnet on the path that the extension writes to the console, I believe.

**Comment by mohitNarang** [comment]
> @mohitNarang how did you do that? I don't see any configurable path on the extension's settings. When the extension is initializing it writes:
> 
> ```
> Using dotnet configured on PATH
> Dotnet path: /usr/local/share/dotnet/dotnet
> ```
> 
> The path to dotnet in PATH is correct `/usr/local/share/dotnet`, the thing is that the executable inside that folder is also called dotnet, hence the double dotnet on the path that the extension writes to the console, I believe.

Here is the image: 
![image](https://github.com/microsoft/vscode-dotnettools/assets/3862580/9b4f70d9-64d8-4dde-8c62-fb6562f1ee77)
I litereally go to settings and find the setting for the extension. I have added the screenshot for your reference. Let me know if it worked for you.

**Comment by nagilson** [comment]
There are several different issues here. One is a GLIB dependency issue which is a missing dependency due to a bad .NET installation. If you hit this error you need to install the dependencies https://github.com/dotnet/core/blob/main/release-notes/6.0/linux-packages.md to get it to work, or use the .NET SDK installer that is build into C# DevKit via the walkthrough.

The original issue is about the runtime being for the incorrect architecture. 

The issue raised by mohit is an issue with snap installs and canonical. This is a symbolic link which needs to be created and is tracked here https://github.com/canonical/dotnet-snap/issues/13#issuecomment-2215186086

The issue raised by justin is an issue about the time for the language server to start taking too long.

For people who are experiencing different issues from the original issue, please file a different one. It will not be helpful to try to diagnose 4-5 different issues in the same thread.
