### ISSUE TITLE
[BUG] Add new file failed from Solution Explorer.

### ISSUE THREAD

**Issue by alfadb** [microsoft/vscode-dotnettools#500]
### Describe the Issue

When I create a new class from solution explorer, I got a error.

### Steps To Reproduce

1. Add new Class from Solution Explorer:

- <img width="244" alt="1694267750870" src="https://github.com/microsoft/vscode-dotnettools/assets/3182249/4b09c56b-7f03-4fb4-a31e-628ab5d3076d">

- <img width="456" alt="1694267781078" src="https://github.com/microsoft/vscode-dotnettools/assets/3182249/e53fac61-742e-4885-a28a-5cc979960e07">

- <img width="456" src="https://github.com/microsoft/vscode-dotnettools/assets/3182249/ff17ee76-1d1e-4c8f-82c4-187c7a87a77b">

2. Get Error:
![image](https://github.com/microsoft/vscode-dotnettools/assets/3182249/e0ce8d3c-515a-4c66-8150-77a9a94d7f64)
```
Error running command csdevkit.addNewFile: Failed with ExitCode(103)
Details
No templates or subcommands found matching: 'class'.
Did you mean one of the following templates?
   dotnet new classlib
Did you mean one of the following subcommands?
   dotnet new list

To list installed templates similar to 'class', run:
   dotnet new list class
To search for the templates on NuGet.org, run:
   dotnet new search class


For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
. This is likely caused by the extension that contributes csdevkit.addNewFile.
```

### Environment Information

- Windows 11 + RemoteSSH to Archlinux
- VSCode Version: 1.82.0
- Extension Version: v0.4.10 (Last released 2023-9-8, 02:12:19)

**Comment by smitpatel** [comment]
This has been fixed in next release. Should be available in 0.5.*

**Comment by alfadb** [comment]
> This has been fixed in next release. Should be available in 0.5.*

Ok, Thanks.

**Comment by simon125** [comment]
Same here, I'm still getting the same error when I'm trying to create new file (Class etc) 

**Environment Information**
Ubuntu 20.04.5 LTS
VSCode Version: 1.84.2
Extension Version: .NET Extension Pack v1.0.13

**Comment by theekshanak** [comment]
Same here, I'm getting the same error when I try to create a new file using Solution Explorer 

Environment Information
macOS Sonoma : 14.1.2 (23B92)
VSCode version: 1.85.1 (Universal)
Extension Version: v1.1.16

**Comment by yoav-melamed** [comment]
I'm also having the same issue.

**Environment**
macOS Sonoma : 14.1.2
Apple M2 Pro ARM64
VSCode version: 1.85.1
Extension Version: v1.1.16

**Comment by smikelson75** [comment]
I'm having the same issue when I utilize the WSL Ubuntu 20.04 but everything works just fine when I use the C# Dev Kit natively on Windows. Please fix the WSL Ubuntu.

Environment
Windows 11 running Ubuntu 20.04.6 LTS via WSL
VSCode: 1.85.1
Extension version: 1.2.5 (Pre-release) or 1.2.4

**Comment by zhangr4** [comment]
I also have the same issue here.

Environment:
Windows 11
VSCode: 1.85.1
Extension version(C# Dev Kit): v1.1.16

**Comment by ErikSvaleng** [comment]
> I also have the same issue here.
> 
> Environment: Windows 11 VSCode: 1.85.1 Extension version(C# Dev Kit): v1.1.16

Same setup, same issue. Also same issue when I switch to the Pre-Release version.

**Comment by brandochn** [comment]
I'm having the same issue

Environment:
Windows 10 running Ubuntu 22.04.3 LTS via WSL2
VSCode: 1.85.1
Extension version: 1.2.7

**Comment by ErikSvaleng** [comment]
> Same setup, same issue. Also same issue when I switch to the Pre-Release version. Creating folders works just fine

With C# Dev kit now at v.1.2.7, I no longer get this error.

**Comment by uhback** [comment]
I'm still having the same issue:

> Error running command csdevkit.addNewFile: Failed with ExitCode(6) Details No templates found matching: 'class'. To list installed templates, run: dotnet new --list To search for the templates on NuGet.org, run: dotnet new class --search . This is likely caused by the extension that contributes csdevkit.addNewFile.

Environment:
- MacOS: 13.1
- VSCode version: 1.85.2
- C# Extension version: 2.15.30
- C# Dev Kit Extension version: 1.2.7

**Comment by Ludogo** [comment]
i had the same issue using linux Ubuntu
I was able to solve it by : 
`dotnet new --install Vio.Dotnet.Templates`

**Comment by jnomikos** [comment]
> dotnet new --install Vio.Dotnet.Templates

This fixed the issue for me as well

**Comment by majew7** [comment]
Yes, as a workaround, this worked for me too: `dotnet new --install Vio.Dotnet.Templates`.

Then using "Add New File..." menus worked.

**Context**
VSCode: 1.86.0
C#: 2.15.30
C# Dev Kit: 1.3.10

**Comment by RodrigoooSC** [comment]
Funcionou para mim também: dotnet new --install Vio.Dotnet.Templates.

Contexto
VSCode: 1.87.1
C#: 2.22.3
Kit de desenvolvimento C#: 1.4.29

**Comment by liupeng5843** [comment]
dotnet new --install Vio.Dotnet.Templates is work for macos

**Comment by smitpatel** [comment]
Fixed in version 1.9.55
