### ISSUE TITLE
[BUG]  Solution explorer and entity framework core not loading

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#704]
### Describe the Issue

Copied from https://github.com/dotnet/vscode-csharp/issues/6653, originally filed by @muneebusmani

Type: <b>Bug</b>

solution explorer is not loading

Extension version: 2.0.0
VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows 11 Pro

More details:
<display>@dibarbet</display>
<p>
<hr>
<h3>C# output:</h3>
<hr>

    Installing Razor Telemetry Version = 7.0.0-preview.23528.1...
    Platform: win32, x86_64

    Downloading package 'Razor Language Server Telemetry (Windows / x64)' (9395 KB).................... Done!
    Validating download...
    Integrity Check succeeded.
    Installing package 'Razor Language Server Telemetry (Windows / x64)'

    Finished

    Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
    The architecture of the .NET runtime (x86) does not match the architecture of the extension (x64).
    Dotnet path: c:\Users\munee\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.13~x64\dotnet.exe
    Activating C# + C# Dev Kit + C# IntelliCode...
    waiting for named pipe information from server...
    [stdout] {"pipeName":"\\\\.\\pipe\\a1a52dc9"}
    received named pipe information from server
    attempting to connect client to server...
    client has connected to server
    [Info  - 1:54:25 AM] [Program] Language server initialized</p>
<hr>
<p>
<h3>C# Dev Kit output :</h3>
<hr>
    Starting Spawn .NET server...
    Starting Open a solution...
    Starting Open a solution with environment service...
    Starting Clear environment...
    Using local .NET runtime at "c:\Users\munee\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.13~x64\dotnet.exe"
    Using runtime installed in SDK.
    .NET server started and IPC established in 8295ms
    Completed Spawn .NET server (14026ms)
    Completed Clear environment (15439ms)
    Completed Open a solution with environment service (15572ms)
    Starting Restore solution...
    Completed Open a solution (15708ms)
    Starting NuGet restore for the solution.
    Starting command: "dotnet.exe" restore C:\Users\munee\RiderProjects\Fresh Start\Fresh Start.sln --interactive...
    Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed.
    Completed command: "dotnet.exe" restore C:\Users\munee\RiderProjects\Fresh Start\Fresh Start.sln --interactive (8190ms)
    Completed NuGet restore.
    Completed Restore solution (8197ms)
</p>
<p>
<hr>
<h3>when i expand the solution explorer, This error notification pops up:</h3>
<hr>
    Activating the "Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.
</p>
<br><br>
<hr>
<br><br>
<br><br>
i Tried using insiders versions but it still doesnt has this bug fixed, and there is also one more issue in vs code,
whenever i write code into my Program.cs file in an asp.net project, or any other project , it doesnt suggest available classes, methods etc

**Comment by dibarbet** [comment]
> Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed. 

and

> Activating the "Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.

appear to be failures on the devkit side

**Comment by muneebusmani** [comment]
Did you check if you can reproduce this bug or not?

**Comment by muneebusmani** [comment]
it was a config bug, i was having other issues too so i reinstalled windows, works fine , now i dont even use solution explorer now lol because it doest show non-csproj projects

**Comment by lifengl** [comment]
Based on the conversation, this issue was resolved.  It usually happens when the X86 version of the SDK/runtime was installed on the machine, and it appears before the x64 version of the runtime/SDK installation. This will lead a wrong dotnet to be used. The extension is compiled to x64 binaries. Although both x64/x86 executable may run on the machine, they cannot run inside the same process.

**Comment by vriesj** [comment]
This issue is still present in the latest release

The error is not informative
![image](https://github.com/microsoft/vscode-dotnettools/assets/122781544/85214b18-a4da-47d7-a2ec-795f69f63b38)

and the visual UI state becomes bugged
![image](https://github.com/microsoft/vscode-dotnettools/assets/122781544/227f9dbe-e4cc-4fe3-a51e-c89aa1b56993)

this issue should not have been closed.

**Comment by tmakin** [comment]
I received the error above on an M1 Mac when I installed the x64 instead of the arm64. All sorted when I installed the right one 🙄

**Comment by muneebusmani** [comment]
as i and others stated , it is an issue with the sdk, if u install the wrong version by mistake , then this happens, just completely remove the sdk along with the ~/.dotnet (Same in *nix/window) , then it will be resolved
________________________________

**Comment by vriesj** [comment]
@muneebusmani that's fine from a developers perspective, and we now know what causes this issue, but you can't expect every end-user to find this thread and manually resolve the issue by doing an `rm -rf` on their entire `~/.dotnet` directory.

**Comment by muneebusmani** [comment]
u got a point

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lifengl** [comment]
@vriesj , any suggestion on what you expect from the extension in this case?  maybe a better error message?  do you see any warning message popping up to report mismatching platform between the extension and the SDK on the right corner of the vs code window?  Maybe the message is mostly targeting users who uses M1 Mac, and installed X64 SDKs earlier. It is relatively rare people ran into the similar issue on Windows.

You can open a new suggestion issue to track this. The problem of issues coming from machine configurations is that it is hard to have an instruction to work for everyone to fix the issue. With scripts, SDK can be installed to any random folder, on a machine level, user level, or repo level, and some scripts manipulate environment variables, so you may get things to work in one command shell, but not another one.  So deleting ~/.dotnet might work for you or might not. 

maybe the only key part is that you have to install a correct version of SDK and ensure it is in the front (or earlier than other SDK locations) in the PATH environment variable in the session you start VS code.

**Comment by muneebusmani** [comment]
Basically, deleting dotnet doesn't work, only solution is reset the device and use dotnet either in wsl if u use windows or use a docker pre-made setup for dotnet, note: purging dotnet doesn't work if u have this issue, there is very small chance that it Will

**Comment by teejstroyer** [comment]
On macOS I had success by removing my homebrew installation of dotnet!

Wish I could install dotnet versions with dotnet.

**Comment by ThomasCode92** [comment]
I'm utilizing WSL along with asdf, and I've installed dotnet version 8.0.100. Despite attempting the solutions mentioned earlier and adjusting the settings as described, I still encounter the same error.

```json
"dotnetAcquisitionExtension.existingDotnetPath": [
    {
      "extensionId": "ms-dotnettools.csdevkit",
      "path": "/home/thomas/.asdf/installs/dotnet/8.0.100/dotnet"
    }
  ],
```

**Comment by Tratcher** [comment]
I'm hitting this on WSL:

```
Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
    Microsoft.ServiceHub.Controller.LocationService.OnHostExit(Microsoft.ServiceHub.Controller.HostInfo, int)
    Microsoft.ServiceHub.Controller.LocationService.StartNewHostAsync.AnonymousMethod__0(object, System.EventArgs)
    System.Diagnostics.Process.RaiseOnExited()
    System.Diagnostics.Process.CompletionCallback(object, bool)
    System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, object)
    System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, object)
    System.Threading.PortableThreadPool.CompleteWait(System.Threading.RegisteredWaitHandle, bool)
    System.Threading.ThreadPoolWorkQueue.Dispatch()
    System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

The above cleanup steps haven't helped.

**Comment by dietbrand** [comment]
> On macOS I had success by removing my homebrew installation of dotnet!
> 
> Wish I could install dotnet versions with dotnet.

I've had more luck using Isen-ng's taps

```
brew tap isen-ng/dotnet-sdk-versions
brew install --cask dotnet-sdk8-0-100
```

**Comment by jnomikos** [comment]
I ran into this bug as well on Ubuntu 22.04. Turns out I had the snap package of dotnet as well as the one that you would install via the scripted install here: https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install

I figured this out by doing "whereis dotnet".

I solved this issue on my computer by both doing 

`rm -rf ~/.dotnet`

and then also uninstalling the snap package by doing}

`sudo snap remove dotnet-sdk`

Then I reinstalled dotnet by following the same guide:
`https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install`


And bam, things worked for me on vscode without error. In my situation, the source of the problem appeared to be the snap package.

**Comment by impuLssse** [comment]
> On macOS I had success by removing my homebrew installation of dotnet!
> 
> Wish I could install dotnet versions with dotnet.

I love u, thx ^-^

**Comment by FDQM** [comment]
Hi, I have the Solution Explorer issue in a M1 Pro, I already reinstalled the .NET and some of the extensions in VSCode, here is my `dotnet --info` if that might help.

`.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.3
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /Users/[User]/.vscode-dotnet-sdk/.dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/Users/[User]/.vscode-dotnet-sdk/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/Users/[User]/.vscode-dotnet-sdk/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/Users/[User].vscode-dotnet-sdk/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  arm64 [/usr/local/share/dotnet]
    registered at [/etc/dotnet/install_location_arm64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download`

**Comment by Kyu** [comment]
> Basically, deleting dotnet doesn't work, only solution is reset the device and use dotnet either in wsl if u use windows or use a docker pre-made setup for dotnet, note: purging dotnet doesn't work if u have this issue, there is very small chance that it Will  

This is a very strange bug, considering that I've only ever installed .NET using Visual Studio Installer, which should be the default way

**Comment by PhatAdam** [comment]
> On macOS I had success by removing my homebrew installation of dotnet!
> 
> Wish I could install dotnet versions with dotnet.

THIS!!!! FIXED MY ISSUE
