### ISSUE TITLE
[BUG] .Net MAUI VSCode Run and Debug script doesn't  properly set the sdk path

### ISSUE THREAD

**Issue by emmauss** [microsoft/vscode-dotnettools#745]
### Describe the Issue

When using the `Run and Debug` action for an Android project, the script run in the integrated terminal uses the wrong type of quotes for the `AndroidSdkDirectory` on running `dotnet`. Below is the command generated;
```
dotnet build -t:Run -p:Configuration=Debug -p:AdbTarget=-s%20fbb7bc0f -p:AndroidAttachDebugger=true -p:AndroidSdbTargetPort=62788 -p:AndroidSdbHostPort=62788 -p:AndroidSdkDirectory='C:\Android\vs\android-sdk\'  <project_path>
```
This command throws the following error;
```
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.47\tools\Xamarin.Android.Tooling.targets(70,5): error XA5300: The Android SDK directory could not be found. Install the Android SDK by following the instructions at: https://aka.ms/dotnet-android-install-sdk
```
Running the command as is also throws the same error. Running the command with `""` instead of `''` successfully builds and runs in terminal;
```dotnet build -t:Run -p:Configuration=Debug -p:AdbTarget=-s%20fbb7bc0f -p:AndroidAttachDebugger=true -p:AndroidSdbTargetPort=62788 -p:AndroidSdbHostPort=62788 -p:AndroidSdkDirectory="C:\Android\vs\android-sdk\"  <project_path> ```

### Steps To Reproduce

1. Create an Android dotnet or MAUI project.
2. Run and Debug. Select the Android project to debug

### Expected Behavior

`dotnet` should detect the sdk passed in the command and build successfully.

### Environment Information

OS: Windows 11
VSCode: 1.84.2
MAUI extension: 0.5.50

> VS bug [#1921030](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1921030)

**Comment by mauroa** [comment]
This issue has been fixed on latest .NET MAUI release version. Please ensure to also update C# and C# DevKit to latest pre-release versions as well. Thanks

**Comment by Angelinsky7** [comment]
i still have a similar issue with vscode and maui extensions 1.6.16

`cmd.exe /d /c dotnet build -t:Run -p:Configuration=Debug -f net9.0-android -p:AdbTarget=-s%20emulator-5554 -p:AndroidAttachDebugger=true -p:AndroidSdbTargetPort=54563 -p:AndroidSdbHostPort=54563 -p:CustomAfterMicrosoftCSharpTargets="c:\Users\Steven\.vscode\extensions\ms-dotnettools.dotnet-maui-1.6.16-win32-x64\dist\resources\Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile="C:\Users\Steven\AppData\Local\Temp\dotnet-maui\maui-vsc-3b5a9936-32ea-449e-b75a-65c285066827.json" "-p:JavaSdkDirectory="C:\Program Files (x86)\Android\openjdk\jdk-17.0.12"" -p:XamlTools="c:\Users\User\.vscode\extensions\ms-dotnettools.csharp-2.55.29-win32-x64\.xamlTools" E:\Projects\netcore_test\MauiApp1\MauiApp1\MauiApp1\MauiApp1.csproj"`

the sdk path is not correct : `"-p:JavaSdkDirectory="C:\Program Files (x86)\Android\openjdk\jdk-17.0.12""`
and the project path neither: `E:\Projects\netcore_test\MauiApp1\MauiApp1\MauiApp1\MauiApp1.csproj`

if by hand i remove the faulty `"` in the sdk and add the missing ones in the project path, it works correctly

giving me : 

`cmd.exe /d /c dotnet build -t:Run -p:Configuration=Debug -f net9.0-android -p:AdbTarget=-s%20emulator-5554 -p:AndroidAttachDebugger=true -p:AndroidSdbTargetPort=54563 -p:AndroidSdbHostPort=54563 -p:CustomAfterMicrosoftCSharpTargets="c:\Users\Steven\.vscode\extensions\ms-dotnettools.dotnet-maui-1.6.16-win32-x64\dist\resources\Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile="C:\Users\Steven\AppData\Local\Temp\dotnet-maui\maui-vsc-3b5a9936-32ea-449e-b75a-65c285066827.json" -p:JavaSdkDirectory="C:\Program Files (x86)\Android\openjdk\jdk-17.0.12" -p:XamlTools="c:\Users\User\.vscode\extensions\ms-dotnettools.csharp-2.55.29-win32-x64\.xamlTools" "E:\Projects\netcore_test\MauiApp1\MauiApp1\MauiApp1\MauiApp1.csproj"`
