### ISSUE TITLE
[BUG] Activating the "Microsoft.VisualStudio.ProjectSystem.Query.Remoting.QueryExecutionService (0.2)" service failed.

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#840]
### Describe the Issue

This is copied from a comment on https://github.com/dotnet/vscode-csharp/issues/6777#issuecomment-1879102010, originally posted by @dpoole73
------------------------------------

I do see this error when opening code:

Activating the "Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.

I also see this in the C# Dev Kit - Test explorer log:

```
Created Test Controller
Using vstest from dotnet sdk in [/usr/local/share/dotnet/x64/sdk/8.0.100].
Initialized Test Explorer Server [67339]
Test Store Folder: /Users/dpoole/Library/Application Support/Code/User/workspaceStorage/0cb1155ccf7c948a51123cea767d1c2e/ms-dotnettools.csdevkit
Error opening test data: Failed to deserialize Microsoft.VisualStudio.TestWindow.Records.LogEntry value.
Test data was cleared upon opening.
Test data store opened in 0.001 sec.
Initialized project system provider.
Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "Microsoft.VisualStudio.ProjectSystem.Query.Remoting.QueryExecutionService (0.2)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Failed to start host 'dotnet.projectSystem$C94B8CFE-E3FD-4BAF-A941-2866DBB566FE'. Host exited with code '130' (ErrorKind: HostExited)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetProxyAsync[T](ServiceRpcDescriptor serviceDescriptor, ServiceActivationOptions options, CancellationToken cancellationToken)
RPC server exception:
StreamJsonRpc.RemoteInvocationException: Failed to start host 'dotnet.projectSystem$C94B8CFE-E3FD-4BAF-A941-2866DBB566FE'. Host exited with code '130' (ErrorKind: HostExited)
      at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions serviceActivationOptions, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetProxyAsync[T](ServiceRpcDescriptor serviceDescriptor, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Query.Remoting.QueryClientExecutionEngine.GetExecutionServiceAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Query.Remoting.QueryClientExecutionEngine.SubscribeAsync[TEntity](AsyncQueryable query, IObserver`1 resultsReceiver, IQueryExecutionRemoteContext remoteContext, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.VSCode.ProjectSystemProvider.Service.ProjectSystemProviderService.<InitializeAsync>b__8_0()
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallWithCatchAsync(IInternalLogger log, Func`1 func)

```

Likely because there is no solution shown in the solution explorer is why the Language server is not working?

### Environment Information

i'm seeing very similar issues. I'm running on MacBook with apple silicon using the x64 version of dotnet and setting DOTNET_ROOT

**Comment by dpoole73** [comment]
to clarify, the issue happens with or without specifying DOTNET_ROOT it happens on multiple repos as well.  Let me know what logs I can share to help figure this out, this is really impacting my productivity

**Comment by Michael-Eng** [comment]
@lifengl Can you check to see if we've fixed this issue (or if it still repros?

**Comment by AppliedK** [comment]
Same Issue. Activating the "Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.
I have reinstalled the extensions but the issue is not resolved.
![VS Code Issue](https://github.com/microsoft/vscode-dotnettools/assets/48643671/f2463e11-8b58-41e5-bad5-37208d5ecef6)

**Comment by tophattwaffle** [comment]
I am also having this issue now on a Unity project. Was fine yesterday. 

If I uninstall the Unity extension, and then uninstall the c# dev kit extension, then reinstall them both and reload extensions everything works until the next time I close and re-open VSCode.

**Comment by MyLegend2016** [comment]
> I am also having this issue now on a Unity project. Was fine yesterday.
> 
> If I uninstall the Unity extension, and then uninstall the c# dev kit extension, then reinstall them both and reload extensions everything works until the next time I close and re-open VSCode.

Installed v1.4.29 and everything worked fine!

**Comment by tophattwaffle** [comment]
> Installed v1.4.29 and everything worked fine!

Thanks for the heads up. That seems to be working fine for me now.

**Comment by adam-k-leung** [comment]
> > I am also having this issue now on a Unity project. Was fine yesterday.
> > If I uninstall the Unity extension, and then uninstall the c# dev kit extension, then reinstall them both and reload extensions everything works until the next time I close and re-open VSCode.
> 
> Installed v1.4.29 and everything worked fine!

Can confirm with my Unity project that using v1.5.20 of the C# Dev Kit extension no longer works, but manually downgrading v1.4.29 fixed things.

**Comment by Michael-Eng** [comment]
@lifengl or @jbevain - could we have broken something in project query?

**Comment by ericpohl** [comment]
FWIW downgrading C# Dev Kit to v1.4.29 fixed my similar issues. Using "straight" c#, no Unity or web or anything.

**Comment by mertdorukkalkan** [comment]
Anyone help for this situation i don't know how to downgrade and i cant see the the version of v1.4.29![image](https://github.com/microsoft/vscode-dotnettools/assets/44442334/a48f2303-c836-4616-a17f-176435321e8e)

**Comment by ericpohl** [comment]
@mertdorukkalkan Go to the "C# dev Kit" extension in VSCode. Next to the Uninstall button is a pulldown that will let you install a different version.
![image](https://github.com/microsoft/vscode-dotnettools/assets/31418444/60e5393c-bc65-433f-a52f-4e6ea680e8e2)

**Comment by hbflyhbfly** [comment]
I change the "C# dev Kit" ver from v1.5.20->1.4.29 fixed it.
<img width="668" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/3788918/f5157777-50f4-4e74-ac9c-bccb9be27c1f">

**Comment by Doekin** [comment]
Maybe the extension requires `ASP.NET Runtime` . 
I have `.NET SDK` installed when encountered this problem, and after installing `ASP.NET Runtime`, everything works.

The naming convention is too difficult for me to understand.

**Comment by lifengl** [comment]
@Doekin ,

that is what I thought. The difference between 1.5.20 and 1.4.29 is that the newer version requires ASP.NET runtime. Usually, APS.NET would be installed when .NET SDK is installed. Can you run dotnet --info, which may explain what has been installed on the machine?

**Comment by lifengl** [comment]
hmm... I guess one possibility is that the machine has NET 8 Core runtime, but no ASP.NET runtime. Because ASP.NET runtime is installed with SDK, so maybe the machine running into this problem has newer runtime + older SDKs?  I wonder maybe certain configuration confused the extension so it picks up a wrong runtime configuration.

**Comment by Doekin** [comment]
On Arch, `ASP.NET Runtime` is not installed with SDK. 😂

Running command `pacman -S dotnet-sdk` will install the following paackages
![](https://github.com/microsoft/vscode-dotnettools/assets/105162544/04d58900-551a-4280-b101-68c8c46f4246)
we now have 
![](https://github.com/microsoft/vscode-dotnettools/assets/105162544/32c088b3-cdb8-4757-9d0a-5bd56ceb6b71)
To get `ASP.NET Runtime`, we should run `pacman -S dotnet-sdk`
![](https://github.com/microsoft/vscode-dotnettools/assets/105162544/6956133d-08c8-4398-8d21-a9d80aa542c9)

**Comment by max8rr8** [comment]
Same problem on Arch, fixed by installing `pasman -S aspnet-runtime`

**Comment by AppliedK** [comment]
The issue is resolved by installing the older version of C# Dev Kit. I have now installed v1.5.14 as shown in screenshot below and disabled auto update of extension in VS Code.
To disable auto-update in Visual Studio Code (VS Code), you can follow these steps:
**Open Settings:**
Press Ctrl+, (Windows/Linux) or Cmd+, (Mac) to open the Settings tab.
Alternatively, you can click on File > Preferences > Settings.
**Search for "update":**
In the search bar at the top of the Settings tab, type "update". This will filter the settings to show those related to updates.
**Disable Auto-Update:**
Look for the setting named "Update: Mode" or similar.
Change the value to "none". This setting usually has options like "manual", "default", or "none". Setting it to "none" disables auto-update.
**Save Changes:**
Close the Settings tab, and VS Code will automatically save your changes.
After following these steps, VS Code should no longer automatically update itself. You'll need to manually check for updates and install them if desired.
![VS Code Issue](https://github.com/microsoft/vscode-dotnettools/assets/48643671/9ea2793b-a01d-4b59-ab82-bb85ed08edec)

**Comment by AppliedK** [comment]
> Anyone can help for this situation ? i don't know how to downgrade and i cant see the the version of v1.4.29![image](https://private-user-images.githubusercontent.com/44442334/329643584-a48f2303-c836-4616-a17f-176435321e8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODU5NjAsIm5iZiI6MTcxNTY4NTY2MCwicGF0aCI6Ii80NDQ0MjMzNC8zMjk2NDM1ODQtYTQ4ZjIzMDMtYzgzNi00NjE2LWExN2YtMTc2NDM1MzIxZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDExMjEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZTEwZjE4MTk1NGUyN2UxOTViNjQ3YWFiYzQ5ZGIyNDlmODEyNmJhYThhNWM0ZDIwMDQ5YzlhZmFmNTk0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0Fr-AFOyuCuAsvEmBd7WwWYIRp1yMDHPNpkvTTrCBM)

If you are still having issue. You can install v1.5.14. Look at my comment how to do it.

**Comment by ericpohl** [comment]
@lifengl I finally had a chance to gather logs as you suggested. Starting the 1.5.20 version I get:
```
Error : You must install or update .NET to run this application.

Error : The following frameworks were found:
6.0.22 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
7.0.11 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
```

After installing .NET SDK 8.0 everything works fine now.

**Comment by lifengl** [comment]
thanks @Doekin and @ericpohl,

yeah, it is clear the assumption that the SDK carrying the ASP.Net runtime is incorrect. It is the story to use the Microsoft installation directly. We will find out a solution for this.  

In the meaning time, installing ASP.NET runtime would be a straight workaround.

**Comment by lifengl** [comment]
While the team is working on a fix, to work around this issue:
1, install .NET SDK 8.0 to the machine
2, if you are using Arch Linux, make sure install NET 8 Asp.Net runtime along with the NET 8 SDK to the machine.

**Comment by phadkesharan** [comment]
> I am also having this issue now on a Unity project. Was fine yesterday.
> 
> If I uninstall the Unity extension, and then uninstall the c# dev kit extension, then reinstall them both and reload extensions everything works until the next time I close and re-open VSCode.

Thank you! works fine with v1.4.29

**Comment by yarpenzigren32850** [comment]
Yes, everything worked for me after installation, too.NET SDK

**Comment by ruanmed** [comment]
> While the team is working on a fix, to work around this issue: 1, install .NET SDK 8.0 to the machine 2, if you are using Arch Linux, make sure install NET 8 Asp.Net runtime along with the NET 8 SDK to the machine.

I was having the "Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.  whilst trying to open Solution Explorer, and it seems to be solved after installing the [aspnet-runtime](https://archlinux.org/packages/extra/x86_64/aspnet-runtime/) package that was missing, I thought I only needed the dotnet runtime and SDK packages.

Thanks!

**Comment by tmeschter** [comment]
Note that the latest prerelease version (currently 1.7.4) has a fix such that the ASP.NET runtime will only be needed if you are launching/debugging Aspire app host projects. This bug will be closed when that fix makes it to a release version.
