### ISSUE TITLE
The new solution explorer in VS Code is not loading the project files.

### ISSUE THREAD

**Issue by nitishwebgentle** [microsoft/vscode-dotnettools#86]
Type: <b>Bug</b>

I have installed .Net Core 7.0 on my Windows system and now I installed the C# dev kit preview version to test this extension.
I created the project successfully using VS Code search (Ctrl+Shift+P). This is an Asp.Net Core Web APP project. 
This project is working fine in VS Code old explorer and VS 2022 (using the new .sln file) but the new Solution explorer in VS Code is not loading it stating "A compatible .NET SDK was not found".

Here is the output of the `dotnet -info` command
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

Extension version: 0.1.83
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.09GB free)|
|Process Argv|--crash-reporter-id f78abf1a-0a8c-4c88-8840-c171998ffb69|
|Screen Reader|no|
|VM|0%|
</details>

![image](https://github.com/microsoft/vscode-dotnettools/assets/41483561/3bddbb65-fa0d-4ff2-8602-880ba95e015f)

**Comment by nitishwebgentle** [comment]
These are my VS Code details

Version: 1.79.0 (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by smitpatel** [comment]
I installed extension and created new WebApplication project, it loads correctly for me. Can you share a repro project?
In output window, if you select C# dev kit in dropdown menu, you will see logs from C# dev kit extension. Please share those logs, it may help us point to the cause of the problem you are seeing.

**Comment by nitishwebgentle** [comment]
Here is the C# Dev Kit logs from the output window.

Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
.NET server started and IPC established in 2798ms
Completed Spawn .NET server (2812ms)
Completed Clear environment (3421ms)
Completed Open a solution with environment service (3640ms)
Starting Restore solution...
Completed Open a solution (3758ms)
Completed Restore solution (3924ms)
Starting Expand project...
Completed Expand project (67ms)
**Requested icon not found: StatusInvalid**

![image](https://github.com/microsoft/vscode-dotnettools/assets/41483561/6a4de3b7-3089-4dee-b7bd-6f8280106d28)

**Comment by mkercheval-tva** [comment]
I am having the same issue 

Version: 1.79.0 (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by smitpatel** [comment]
Logs don't show anything problematic so extension is working but if you see that error after restore completes, mostly the suitable SDK is not found in path. Can you check in terminal inside vscode and see what is dotnet --info says there?

**Comment by nitishwebgentle** [comment]
> Logs don't show anything problematic so extension is working but if you see that error after restore completes, mostly the suitable SDK is not found in path. Can you check in terminal inside vscode and see what is dotnet --info says there?

It's already there in my initial question. The info is from the command prompt.

**Comment by smitpatel** [comment]
Related #120

**Comment by lifengl** [comment]
Based on screenshots above, this is likely a duplicated of #24 , which should have been fixed. Please try to update a new version of the extension, and give it a try.

**Comment by mkercheval-tva** [comment]
Still did not resolve my issue. My windows profile name had a space in it, I created a new profile without the space and everything loads correctly.

**Comment by decevy** [comment]
I'm having exactly the same issue! Extensions in pre-release: C# v2.0.249 and C# Dev Kit v0.3.2. Running vscode on a MacBook. Please have a look at this issue, it is not fixed for everyone yet.

**Comment by YuliiaKovalova** [comment]
Hi @decevy , @mkercheval-tva ,

Could you say if homebrew is installed on your machines? 
Thank you!

**Comment by decevy** [comment]
Hey @YuliiaKovalova !

Yes I have homebrew installed! I didn't install the .NET 7 SDK with homebrew though, but downloaded the x64 .pkg installer from the Microsoft page.

**Comment by YuliiaKovalova** [comment]
@decevy , May I ask you to install  C# Dev Kit pre-release v0.2.70 and check if but is still relevant?

**Comment by decevy** [comment]
@YuliiaKovalova, Installed that version and also updated C# extension to v2.0.249 (since it asked). Issue unfortunately persists. 
![image](https://github.com/microsoft/vscode-dotnettools/assets/8865946/0c03fc75-6dd4-44e7-bcff-4bb84d95d1b7)

**Comment by YuliiaKovalova** [comment]
@decevy, thank you for checking.
While I am investigating , you can try to use this workaround: https://github.com/microsoft/vscode-dotnettools/issues/120#issuecomment-1613973944

**Comment by decevy** [comment]
@YuliiaKovalova I couldn't apply the workaround because I never installed dotnet via homebrew.. I added a DOTNET_ROOT environment variable to my ~/.zshrc, but that didn't change anything either. Thanks for the help, I'll wait for a fix :)

**Comment by YuliiaKovalova** [comment]
Hi @decevy,

Can I ask you for providing more info?
Please open VS Code with the project and type in terminal "dotnet --version". Please share this output.

Also, on project load, please provide logs from these tabs
![image](https://github.com/microsoft/vscode-dotnettools/assets/95473390/27d986b7-5642-4a93-a9db-668218a39ba7)

Thank you for cooperating with us!

**Comment by decevy** [comment]
Hi @YuliiaKovalova, sure thing!

```
dotnet --version
7.0.305
```

C# output:
```
Dotnet path: /Users/decevy/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.9/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
```

C# Dev Kit output:
```
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
.NET server started and IPC established in 3403ms
Completed Spawn .NET server (3630ms)
Completed Clear environment (4152ms)
Completed Open a solution with environment service (4384ms)
Starting Restore solution...
Completed Open a solution (4584ms)
Completed Restore solution (3820ms)
```

Projects output:
```
2023-07-18 16:38:40.414 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.7
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.305/

Host:
  Version:      7.0.8
  Architecture: x64
  Commit:       4b0550942d

.NET SDKs installed:
  7.0.305 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/local/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2023-07-18 16:38:40.467 [info] Project system initialization finished. 0 project(s) are loaded, and 3 failed to load.

```

**Comment by YuliiaKovalova** [comment]
Hi @decevy,

Thank you for providing the info.
While we are investigating, one of the customers has conducted his investigation with a possible workaround.
https://github.com/microsoft/vscode-dotnettools/issues/120#issuecomment-1640892593

Please, check if it helps to unblock you.

**Comment by decevy** [comment]
Hi @YuliiaKovalova,

I tried this but on my Mac I cannot create a file named "Microsoft.NETCore.App", it automatically adds a '.app' extension. This file was already there, along with "Microsoft.ASPNetCore.App".

<img width="899" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/8865946/274a2618-debf-4f66-a563-5b7fde2c101e">

**Comment by decevy** [comment]
Ahh now it works! I had to add a space at the end of the filenames to look into the folder and copy the file. Then I removed the spaces again from these files. 

Projects get loaded now! Thanks a lot!

**Comment by lifengl** [comment]
The issue was addressed in the scope of https://github.com/dotnet/msbuild/issues/9038.

the extension will pick up the new package in the next pre-release.

**Comment by knextsunj** [comment]
ghghfghfghfghfg
